- components/executive/ExecutiveOverviewCard.tsx
- package.json
- pages/api/executive/analyze-spell/[address].ts
- pages/executive/[proposal-id].tsx
- types/spellData.ts
- yarn.lock
Allows us to get an "available for execution" date that takes office hours into account
> use new spell next cast time feature

- components/executive/ExecutiveOverviewCard.tsx
add 'not yet passed' to exec cards too
> not yet passed

- components/es/ESMHistory.tsx
- pages/esmodule.tsx
- types/esmodule.ts
ESM history now automatically updates when a new burn tx processes
This previously required a page refresh.
> Keep ESM history updated by moving to SWR polling

- components/delegations/DelegateCard.tsx
- pages/delegates/index.tsx
> Add delegate interaction

- PULL_REQUEST_TEMPLATE.md
- components/delegations/DelegateCard.tsx
- components/delegations/modals/DelegateModal.tsx
- components/delegations/modals/Input.tsx
- components/delegations/modals/UndelegateModal.tsx
- components/executive/ExecutiveOverviewCard.tsx
- components/executive/VoteModal.tsx
- components/header/VotingWeight.tsx
- components/index/ExecutiveIndicator.tsx
- components/polling/PollVotingStatus.tsx
- components/polling/VotingWeight.tsx
- components/polling/[poll-hash]/VoteBreakdown.tsx
- components/polling/review/ReviewBox.tsx
- lib/hooks/index.ts
- lib/hooks/useLockedMkr.ts
- lib/hooks/useMkrBalance.ts
- lib/hooks/useMkrDelegated.ts
- lib/hooks/useVotedProposals.ts
- lib/polling/getVotingWeightCopy.ts
- lib/utils.ts
- package.json
- pages/delegates/index.tsx
- pages/delegates/me.tsx
- pages/executive.tsx
- pages/executive/[proposal-id].tsx
- pages/polling.tsx
- stores/accounts.ts
- stores/ballot.ts
- stores/transactions.ts
- yarn.lock
Updates how vote delegate is used in accounts store
Checks for vote delegate existence in vote modal and uses vote delegate to vote on executive if it exists
You will need the latest dai.js changes on `vote-delegation` branch to test this locally.
> Delegate executive voting

- components/executive/VoteModal.tsx
- lib/hooks/index.ts
- lib/hooks/useAllSlates.ts
- lib/hooks/useHat.ts
- lib/hooks/useSpellData.ts
- pages/executive.tsx
- pages/index.tsx
https://app.clubhouse.io/dux-makerdao/story/270/fix-executive-vote-modal-mkr-amounts
Fixes layout issue in the vote modal
Refactors vote modal calls into reusable hooks
1. Go to `/executive` with a connected account
2. Click "Vote"
3. Ensure modal MKR displays are correct
Before:
After:
> Vote modal layout fix and refactor

- __tests__/helpers.tsx
- __tests__/pages/delegates/me.tsx
- pages/delegates/me.tsx
- stores/transactions.ts
https://app.clubhouse.io/dux-makerdao/story/225/end-to-end-testing-of-mvp-delegation
-
Adds an integration test for creating a vote delegate using the testchain as a backend. 
Test covers:
- connecting an account
- clicking the create button
- verifying modal updates during transaction state changes
- verifying page update after transaction is complete
Also includes the fix from #107 which was uncovered during the creation if this test.
-
1. `yarn test delegates/me.tsx`
> Test for creating a vote delegate

- lib/theme.js
https://app.clubhouse.io/dux-makerdao/story/342/broken-executive-layout-for-mobile
> fix: word break

- components/Header.tsx
> Add delegates to mobile menu

- components/delegations/modals/InputDelegateMkr.tsx
disable delegeate/undegate button when input is 0 MKR
> don't allow (un)delegating 0 MKR

- components/delegations/DelegateCard.tsx
- components/es/burnModal/ConfirmBurn.tsx
- components/index/BlogPostCard.tsx
- pages/index.tsx
Delegate card:
Before:
After:
Blog post:
Before:
After:
ESM modal:
Before:
After:
> Dev qa delegations

- components/Footer/LongFooter.tsx
> fix: Change theme UI footer links

- components/Footer/LongFooter.tsx
- components/Footer/ShortFooter.tsx
Request from techops & legal
Removes outdated privacy policy and contact links from footer.
Base branch is master because it seems like it should be a timely upgrade due to legal concerns, but we can merge it into develop if people think that's better.
> remove some footer links

- modules/polls/components/PollVoteHistoryItem.tsx
> fix: Change voted title

- components/polling/PollOverviewCard.tsx
- modules/polls/components/PollVoteHistoryItem.tsx
- stores/accounts.ts
https://www.loom.com/share/e08007271c6b4b969d78eece361b034e
> fix: Link to polls

- modules/polls/components/VotesByAddress.tsx
- pages/api/address/[address]/index.ts
Add network for getting vote contract
Right-align column for MKR support in address breakdown
> Update table columns, vote history on test nets

- lib/maker/web3react/index.ts
- lib/string.ts
- lib/theme.js
- modules/polls/components/VoteBreakdown.tsx
- modules/polls/components/VotesByAddress.tsx
https://app.shortcut.com/dux-makerdao/story/498/replace-walletlink-old-icon
https://app.shortcut.com/dux-makerdao/story/509/vote-breakdown-visuals-overlap-different-network-warning-popup
https://app.shortcut.com/dux-makerdao/story/504/sender-address-last-character-is-trimmed-on-esm-page-after-successfully-burning-mkr
> Vote history QA fixes

- modules/polling/api/fetchAddressPollVoteHistory.ts
- modules/polling/api/fetchPollTally.ts
- modules/polling/helpers/parseRawTally.ts
- pages/api/polling/tally/[poll-id].ts
- pages/executive.tsx
https://app.shortcut.com/dux-makerdao/story/549/long-polling-history-spams-queries-causing-timeout
Caches tally results
Go to poll history for a user with a long vote history
Refresh page after it loads. Notice that it loads faster, server logs cache hits.
> Bug/sc 549/long polling history spams queries causing

- lib/theme.js
- modules/address/components/AddressDetail.tsx
- modules/delegates/components/DelegateVoteHistory.tsx
- modules/polling/components/PollVoteHistoryList.tsx
- modules/polling/components/PollVotePluralityResultsCompact.tsx
- modules/polling/components/PollingParticipationOverview.tsx
- modules/polling/components/YesNoAbstainBar.tsx
None
Adds vote participation breakdown in delegates and non delegates.
Adds load more voting proposals
Go to `/address/0x4c0b1559f1696b47be69e37cb897f3832329ae7a?network=mainnet` or `/address/0xad2fda5f6ce305d2ced380fdfa791b6a26e7f281?network=mainnet#voting-history`
Pizza
> polling participation

- modules/polling/helpers/validator.ts
n/a
Updates categories list for validation when creating a poll
We have a backlog story to dynamically fetch this list in the future. For now, just updating list.
> Add additoinal categories for poll validation

- .circleci/config.yml
> add name for sentry step in circleci

- modules/executive/helpers/getStatusText.ts
> remove unnecessary space

- .circleci/config.yml
- next.config.js
> Disable file tracing sentry error

- modules/polling/api/fetchPolls.ts
- modules/polling/components/PollWinningOptionBox.tsx
- modules/polling/hooks/usePollTally.ts
- pages/_app.tsx
- pages/polling/[poll-hash].tsx
> Fixes: Small bugs release

- modules/address/components/AddressDelegatedTo.tsx
- modules/address/components/AddressDetail.tsx
- modules/address/components/AddressMKRDelegatedStats.tsx
- modules/app/components/layout/header/VotingWeight.tsx
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegationHistory.ts
- modules/delegates/components/DelegatedByAddress.tsx
- modules/delegates/types/delegate.d.ts
- modules/delegates/types/delegatesAPI.d.ts
- modules/mkr/hooks/useMKRVotingWeight.ts
- modules/polling/components/PollingParticipationOverview.tsx
- package.json
- pages/address/[address]/index.tsx
- pages/api/address/[address]/delegated-to.ts
- pages/api/address/[address]/stats.ts
- yarn.lock
https://app.shortcut.com/dux-makerdao/story/765/add-delegated-mkr-to-list-to-account-page
Adds MKR delegated to in the address detail page
Go to a delegate, find people who delegated to him, click on the address and go to the detail, see MKR delegated to that address , time and transaction
> fetch the delegates an address has delegated to

- lib/theme.js
- pages/index.tsx
Adds play icon to "how to vote" landing page button
> Play button icon

- modules/address/components/AddressIconBox.tsx
- modules/comments/api/getExecutiveComments.ts
- modules/comments/api/getPollComments.ts
- modules/comments/components/CommentItem.tsx
- modules/comments/components/PollComments.tsx
- modules/comments/types/executiveComment.ts
- modules/comments/types/pollComments.d.ts
- modules/executive/components/VoteModal/DefaultView.tsx
- modules/polling/stores/ballotStore.ts
- pages/api/comments/executive/add/[address].ts
- pages/api/comments/polling/add.ts
> store vote proxy info

- modules/app/components/layout/Footer/LongFooter.tsx
Adds API docs to developer links on long footer
Removes rocket chat link
Updates to open social links in new tab
> Update long footer with new links

- __tests__/pages/esmodule.spec.tsx
- __tests__/pages/executive.spec.tsx
- __tests__/pages/polling.spec.tsx
- modules/polling/components/__tests__/polling.spec.tsx
This PR is mostly just updating test descriptions to be more accurate and unnesting a test for ESM
> Test description updates

- modules/delegates/api/fetchMKRWeightHistory.ts
Update to account for new year across start and end
To test go to any delegate page and make sure the chart loads correctly.
> Fix maker weight over time display issue

- pages/api/comments/polling/add.ts
> Use insertMany for poll comments

- __tests__/pages/polling/[poll-hash].spec.tsx
- modules/polling/components/VoteBreakdown.tsx
- pages/polling/[poll-hash].tsx
Add test for rendering poll detail page
> Chore/sc 992/add test to poll detail check whether tabs

- modules/address/components/AddressDelegatedTo.tsx
- modules/address/components/AddressDetail.tsx
> Add delegate names to addresses

- cypress/support/commons/index.ts
- lib/theme.js
- modules/app/components/layout/Header.tsx
- modules/app/components/layout/header/AccountSelect.tsx
- modules/app/components/layout/header/NetworkSelect.tsx
- modules/web3/components/ConnectNetworkButton.tsx
> add network connect component to header

- cypress/integration/account.spec.ts
- cypress/integration/polling/review.spec.ts
- cypress/support/commons/index.ts
- modules/address/components/AddressIconBox.tsx
- modules/app/components/Tabs.tsx
- modules/app/context/AccountContext.tsx
- modules/comments/components/CommentTextBox.tsx
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegationHistory.ts
- modules/delegates/api/fetchMKRWeightHistory.ts
- modules/mkr/components/Withdraw.tsx
- modules/polling/api/fetchAddressPollVoteHistory.ts
- modules/polling/api/fetchAllCurrentVotes.ts
- modules/polling/api/fetchPollBy.ts
- modules/polling/api/fetchVotesByAddress.ts
- modules/polling/components/PollBar.tsx
- modules/polling/components/PollOverviewCard.tsx
- modules/polling/components/PollVoteHistoryItem.tsx
- modules/polling/components/PollingParticipationOverview.tsx
- modules/polling/helpers/parseRawOptionIdRankedChoiceOption.ts
- modules/polling/helpers/utils.ts
- modules/polling/stores/ballotStore.ts
- modules/polling/types/pollVote.d.ts
- modules/web3/helpers/switchToNetwork.ts
- pages/account.tsx
- pages/api/address/[address]/stats.ts
- pages/polling/review.tsx
- Fixes votePoll method
- Adds a list of voted Polls after submitting the ballot
- Adds test to withdraw from chief in the account page
- Adds test to verify poll comments working: WIP, need ethers to sign comments transaction
> Withdraw chief test, polling comments test, fix vote poll bug

- cypress/support/commons/index.ts
- lib/theme.js
- modules/app/components/layout/Header.tsx
- modules/app/components/layout/header/AccountSelect.tsx
- modules/app/components/layout/header/NetworkAlertModal.tsx
- modules/app/components/layout/header/NetworkSelect.tsx
- modules/web3/components/ConnectNetworkButton.tsx
- modules/web3/hooks/useEagerConnect.ts
> Network connect button

- cypress/integration/polling/poll-detail.spec.ts
- pages/polling/[poll-hash].tsx
fix poll-detail.spec.ts by passing in the correct network to `fetchPollBySlug`.
> look for the network param to fetch polls from that network

- modules/address/components/AddressDetail.tsx
- modules/app/components/ErrorBoundary.tsx
- modules/app/components/Tabs.tsx
- modules/app/components/layout/Header.tsx
- modules/app/components/layout/header/AccountSelect.tsx
- modules/delegates/components/DelegateVoteHistory.tsx
- modules/home/components/ExecutiveCard.tsx
- modules/polling/components/PollOverviewCard.tsx
- package.json
- pages/_app.tsx
- pages/account.tsx
- pages/address/[address]/index.tsx
- pages/delegates/index.tsx
- pages/esmodule.tsx
- pages/executive.tsx
- pages/executive/[proposal-id].tsx
- pages/index.tsx
- pages/polling.tsx
- pages/polling/[poll-hash].tsx
- yarn.lock
Wraps pages and components in a ErrorBoundary that limites the spread of error and crashing of the app.
> Add error boundary through app components

- pages/index.tsx
> fix:  overflow issue

- modules/app/components/layout/header/ColorModeToggle.tsx
Fix dark mode scrollbar issue.
Fixes #333 
Added logic to toggle color scheme of HTML
> fix: dark mode scrollbar issue

- modules/app/helpers/getVoteProxyAddresses.ts
- modules/mkr/helpers/getMKRVotingWeight.ts
- modules/polling/components/VotingWeight.tsx
- pages/api/address/[address]/delegated-to.ts
- pages/polling/[poll-hash].tsx
Update address page to better account for vote proxies
Check that the following pages all show the same information:
Hot: `/address/0x14341f81dF14cA86E1420eC9e6Abd343Fb1c5bfC`
Cold: `/address/0x1f33AF426CE267924BE827B16A3f5E4Afcb89a63`
Proxy: `/address/0xe845332d7b4e454a836d05267e1c8f098b89c401`
> Update vote proxy checks

- cypress/integration/polling.spec.tsx
- cypress/integration/polling/review.spec.ts
- cypress/support/commons/index.ts
- modules/home/components/ExecutiveIndicator.tsx
- modules/polling/components/PollOverviewCard.tsx
- pages/polling/[poll-hash].tsx
https://app.shortcut.com/dux-makerdao/story/1060/display-poll-id-on-poll-detail-page
> Display poll ID on poll detail page [sc-1060]

- modules/gql/queries/uniswapV3MkrSupply.ts
- modules/mkr/components/MkrLiquiditySidebar.tsx
https://app.shortcut.com/dux-makerdao/story/1135/implement-improved-mkr-liquidity-panel
Adds uniswap v3 and compound liquidity to liquidity panel
Pools protocols together, adds expanding detail sections
Go to exec page, see liquidity updates in sidebar ✨
> Feature/sc 1135/implement improved mkr liquidity panel

- modules/address/components/AddressDetail.tsx
- pages/account.tsx
- pages/address/[address]/index.tsx
- pages/api/address/[address]/delegated-to.ts
Remove duplicate delegation events
Issue can be seen in staging here: https://staging-vote.vercel.app/address/0xc54c3691419c2996eb6e76b421e7f1132ab0ee7a
> Filter out duplicate delegation events

- lib/theme.js
- modules/delegates/api/fetchDelegates.ts
- modules/delegates/components/DelegateCard.tsx
- modules/delegates/components/DelegatesSort.tsx
- modules/delegates/types/delegate.d.ts
- modules/executive/api/fetchExecutives.ts
- modules/executive/components/DateFilter.tsx
- modules/gql/queries/lastPollVote.ts
- modules/polling/api/fetchLastPollvote.ts
- modules/polling/components/PollCategoryTag.tsx
- modules/polling/types/pollVote.d.ts
- package.json
- pages/api/delegates/index.ts
- pages/api/delegates/names.ts
- pages/delegates/index.tsx
- pages/executive.tsx
- pages/polling.tsx
Hotfix for delegates api timeout and other small ui fixes
> Hotfix , delegates api timeout

- modules/app/client/analytics/analytics.constants.ts
- modules/app/components/TxFinal.tsx
- modules/delegates/components/DelegateCard.tsx
- modules/delegates/components/TopDelegates.tsx
- modules/delegates/components/modals/DelegateModal.tsx
- modules/delegates/components/modals/TxDisplay.tsx
- modules/delegates/components/modals/UndelegateModal.tsx
- modules/esm/components/BurnModal.tsx
- pages/index.tsx
Add UI for top delegators
Improve modal UI for delegating
> Add UI for top delegators

- pages/executive/[proposal-id].tsx
- pages/polling/[poll-hash].tsx
> try pre-building a smaller amount of pages with static paths

- pages/executive/[proposal-id].tsx
- pages/polling/[poll-hash].tsx
> try pre-building a smaller amount of pages with static paths (#388)

- lib/theme.js
- modules/app/stores/uiFilters.ts
- modules/delegates/components/DelegatesSort.tsx
- modules/executive/components/ProposalsSortBy.tsx
- pages/delegates/index.tsx
- pages/executive.tsx
https://app.shortcut.com/dux-makerdao/story/1004/align-sorting-and-filtering-buttons
Fixes a few visual things with the filters as lined out in the ticket
Quickly change between polling/executive/delegates pages and see the filters are aligned correctly
> some UI fixes for filters and pages

- modules/comments/components/PollComments.tsx
- modules/delegates/api/fetchDelegates.ts
Updates the check for a delegate so that comments from hot wallet/delegate deployer wallets get connected to comment
> Update delegate check

- cypress/integration/polling/poll-detail.spec.ts
- modules/polling/api/fetchAllCurrentVotes.ts
- modules/polling/api/fetchLastPollvote.ts
- modules/polling/api/fetchPollTally.ts
- modules/polling/api/fetchRawPollTally.ts
- modules/polling/api/fetchVotesByAddress.ts
- modules/polling/helpers/__tests__/getPollTally.spec.ts
- modules/polling/helpers/getPollTally.ts
- modules/polling/helpers/parseRankedChoiceRawOptionId.ts
Instead of caching the raw tally result, instead cache the fully parsed tally response, if the poll voting period has ended.
> Update tally caching

- modules/app/components/PageLoadingPlaceholder.tsx
- pages/address/[address]/index.tsx
- pages/delegates/index.tsx
- pages/executive.tsx
- pages/index.tsx
- pages/polling.tsx
- pages/polling/review.tsx
> Improve loading page

- __tests__/setup.tsx
- modules/app/components/layout/Footer/LongFooter.tsx
- modules/home/components/Participation.tsx
> Add new card style to participation sections

- __tests__/setup.tsx
- lib/markdown.ts
- lib/utils.ts
- modules/app/components/Makrdown.tsx
- modules/app/components/layout/layouts/Stack.tsx
- modules/comments/api/getCommentsByAddress.ts
- modules/comments/api/getExecutiveComments.ts
- modules/comments/api/getPollComments.ts
- modules/delegates/api/fetchGithubDelegates.ts
- modules/executive/api/fetchExecutives.ts
- modules/home/components/TabsNavigation.tsx
- modules/polling/api/fetchPollBy.ts
- modules/polling/components/ShareVotesModal.tsx
- package.json
- pages/_app.tsx
- pages/cookies-policy.tsx
- pages/executive/create.tsx
- pages/index.tsx
- pages/polling/create.tsx
- pages/terms.tsx
- yarn.lock
Adds sticky tabs navigation and smooth scroll on the homepage
> Tabs navigation

- modules/executive/components/ExecutiveOverviewCard.tsx
- modules/home/components/ResourcesLanding/resources.ts
- modules/polling/components/PollOverviewCard.tsx
Update makerburn description and link hash
> Update makerburn description and link hash

- modules/executive/components/ExecutiveOverviewCard.tsx
Removes code that is fetching spellData client-side that we already have access to from our server-side fetching
> Stop refetching spell data client side

- modules/delegates/api/fetchDelegates.ts
- modules/delegates/components/DelegateDetail.tsx
- modules/executive/api/fetchExecutives.ts
- modules/executive/components/ExecutiveOverviewCard.tsx
* Prevent unnecessary fetch of MKR support with execs
* Prevent unnecessary refetching of spell data on exec cards
* Fix issue with counting of active delegators
> develop > master

- cypress/integration/delegates.spec.ts
- pages/_app.tsx
> Updates and XXS fix.

- .env.sample
- .github/workflows/main.yml
- README.md
- hardhat.config.js
> use infura e2e

- .deepsource.toml
> deepsource file

- lib/github/index.ts
Increase default from 100 to 1000
This was preventing us from fetching the active proposal
> Increase octokit default per page

- modules/contracts/abis/goerli/end.json
- modules/contracts/abis/mainnet/end.json
- modules/executive/helpers/getStatusText.ts
fixes "Date executed" message on landing page.
> display dateExecuted if its not null or undefined

- modules/app/stores/uiFilters.ts
- modules/polling/components/filters/PollsSort.tsx
- pages/polling.tsx
> add PollsSort component & sorting in store

- README.md
- lib/config.ts
- lib/github/index.ts
- lib/utils.ts
- modules/delegates/api/fetchGithubDelegates.ts
- modules/executive/api/fetchExecutives.ts
Default to first token if 2nd or 3rd token not provided
> allow for 3 github tokens

- .github/workflows/e2e.yml
- .github/workflows/unit.yml
Disable e2e for PRs, leave e2e for develop and master push (merge)
> disable e2e for PRs

- modules/polling/components/PollVoteHistoryItem.tsx
- modules/polling/components/VotesByAddress.tsx
- modules/polling/components/__tests__/PollVoteHistoryItem.test.tsx
- modules/polling/components/__tests__/VotesByAddress.test.tsx
- modules/polling/helpers/getVoteColor.ts
> migrate changes for ranked voting

- modules/app/helpers/getVoteProxyAddresses.ts
- modules/delegates/hooks/useDelegateAddressMap.ts
Increase refresh interval for delegate mapping to 30 mins
Add proxy info caching for 60 mins
> Increase refresh interval for delegate mapping, cache proxy info

- modules/comments/components/PollCommentItem.tsx
- modules/polling/components/PollOverviewCard.tsx
- modules/polling/components/PollVoteHistoryItem.tsx
- modules/polling/components/RankedChoiceVoteSummary.tsx
Show ranked choices on comments for poll fixed
also poll overview card include a summary of the ranking
> display ranked choices

- pages/api/github-tokens.ts
Adds `/github-tokens` endpoint to display the rate limits for the github tokens used by the app
https://governance-portal-v2-j43m30ynl-dux-core-unit.vercel.app/api/github-tokens
> create github tokens rate limit api

- modules/polling/components/filters/PollTypeFilter.tsx
- modules/polling/helpers/__tests__/validatePollParameters.spec.ts
- modules/polling/helpers/validatePollParameters.ts
- pages/polling.tsx
https://app.shortcut.com/dux-makerdao/story/1351/updates-to-poll-filters
Restore poll type filter with the new poll metadata
> fix poll parameters filters

- .eslintrc
- lib/cache.ts
- lib/logger.ts
- lib/utils.ts
- modules/app/api/withApiHandler.ts
- modules/app/components/Icon/index.tsx
- modules/comments/api/getCommentsByAddress.ts
- modules/comments/api/insertPollingComments.ts
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegationEventsByAddresses.ts
- modules/delegates/api/fetchGithubDelegates.ts
- modules/executive/api/analyzeSpell.ts
- modules/executive/api/fetchExecutives.ts
- modules/executive/api/fetchSimulationSpellDiff.ts
- modules/executive/api/parseExecutive.ts
- modules/executive/components/VoteModal/DefaultView.tsx
- modules/home/api/fetchAllLocksSummed.ts
- modules/mkr/components/MKRInput.tsx
- modules/polling/api/fetchPollMetadata.ts
- modules/polling/api/fetchPolls.ts
- modules/polling/context/BallotContext.tsx
- modules/web3/connectors/CustomizedBridge.ts
- modules/web3/helpers/ens.ts
- modules/web3/helpers/fetchGasPrice.ts
- modules/web3/helpers/getTrace.ts
- modules/web3/helpers/switchToNetwork.ts
- modules/web3/hooks/useGoerliForkWindowBindings.tsx
- modules/web3/hooks/useInactiveListener.ts
- pages/custom-spell/index.tsx
Replaces console.logs with formatted log messages and adds functions names so we know where the errors come from :
> Update logger implementation

- modules/app/components/layout/header/AccountBox.tsx
- modules/app/components/layout/header/AccountSelect.tsx
Add wallet disconnect button and functionality
Design likely to change in near future
> Add disconnect functionality

- modules/web3/components/AccountNotConnected.tsx
- pages/migration/delegate.tsx
- pages/migration/delegator.tsx
- pages/polling/review.tsx
adds new 2 routes for delegates
/migration/delegators
/migration/delegates
Adds new component to showcase whenever we are accessing a page that requires connection 
Boilerplate code
> boilerplate pages migration

- modules/gql/hooks/useAllDelegates.ts
- modules/home/api/fetchLandingPageData.ts
- modules/home/components/GovernanceStats.tsx
- pages/index.tsx
Fetch landing page delegates from clientside, which will use API cache
> Fetch landing pages delegates from clientside

- modules/address/api/getAddressInfo.ts
- modules/address/components/AddressDetail.tsx
- modules/address/types/addressApiResponse.d.ts
- pages/address/[address]/index.tsx
> add delegate reference in account detail

- modules/delegates/components/DelegateOverviewCard.tsx
- modules/delegates/components/modals/CoreUnitButton.tsx
- modules/migration/components/DelegateExpiryDate.tsx
> Update delegate overview card header

- README.md
fixes the readme for non-dux-people to run the frontend locally
- burn down your machine, resetup from scratch - or just buy a new one
- checkout repo
- blindly follow the instructions for local development
> Fix docs for running locally

- modules/app/client/storage/localStorage.ts
- modules/polling/context/BallotContext.tsx
Add a expiry key to localstorage, if a element has a expiry date set, when fetching it it will return null and delete it
> Add expiry to localstorage

- modules/delegates/api/fetchDelegates.ts
- modules/executive/api/fetchExecutives.ts
- modules/polling/api/fetchPolls.ts
- package.json
* trim data from list endpoints
> trim data from list endpoints (#574)

- modules/polling/api/fetchPollTally.ts
- modules/polling/components/VoteBreakdown.tsx
- modules/polling/components/VotesByAddress.tsx
- modules/polling/components/__tests__/VotesByAddress.test.tsx
Fix %s and number of rounds for failed IRV participation threshold
> Fix %s and number of rounds for failed IRV participation threshold

- lib/theme/buttons.js
- modules/app/components/layout/header/AccountBox.tsx
- modules/app/components/layout/header/AccountSelect.tsx
- modules/app/components/layout/header/NetworkSelect.tsx
- modules/app/components/layout/header/VotingWeight.tsx
- modules/app/context/AccountContext.tsx
- modules/delegates/components/DelegateMKRDelegatedStats.tsx
- modules/delegates/hooks/useDelegateFree.ts
- modules/delegates/hooks/useDelegateLock.ts
- modules/polling/components/poll-vote-input/QuickVote.tsx
- modules/polling/helpers/parsePollMetadata.ts
- modules/polling/types/pollTally.d.ts
https://app.shortcut.com/dux-makerdao/story/1489/implement-redesigned-connected-wallet-modal
Update UI for account/wallet modal
Test out new UI for connecting/changing/disconnecting
> Feature/sc 1489/implement redesigned connected wallet modal

- modules/cache/cache.ts
- modules/cache/getCacheInfo.ts
- pages/api/cache/info.ts
- pages/dashboard/index.tsx
Adds the TTL info for our constant keys to the dashboard
This should give GovAlpha more insight into what is cached and what isn't, and how long until the cache expires
> Add ttl info to dashboard

- modules/polling/components/review/ReviewBox.tsx
> Add loading state and error toast if comments step fails

- modules/app/components/layout/Header.tsx
- modules/polling/components/BallotPollBar.tsx
Before: You voted on 5 of 2 available polls
After: You voted on 5 polls
> Update post-vote ballot box text

- README.md
- package.json
updated version and release docs
> Add release docs and bump version

- modules/comments/components/CommentTextBox.tsx
- modules/polling/components/review/ReviewBox.tsx
Removed comment box for gnosis connection,
Added new eligibility criteria for gnosis signers
> feat: disable comments and gasless voting for gnosis signers

- pages/_app.tsx
> Gasless banner

- modules/polling/components/GaslessBanner.tsx
- modules/polling/components/review/ReviewBox.tsx
Change "free" to "gasless"
Add whitespace
Update button label
> Copy updates

- modules/polling/api/getRelayerBalance.ts
- modules/polling/components/review/ReviewBox.tsx
- modules/polling/helpers/ballotIncludesAlreadyVoted.ts
- modules/polling/helpers/hasMkrRequiredVotingWeight.ts
Adds relayer status section (changes design based on discord convo)
Only shows the failed status if relayer is down, not detected, or unfunded
If relayer is found and funded, it doesn't show the section
> Relayer status updates

- modules/polling/components/review/ReviewBox.tsx
> Small text updates

- modules/cache/constants/cache-keys.ts
- modules/cache/getCacheInfo.ts
- modules/executive/api/fetchExecutivePageData.ts
- modules/executive/api/fetchExecutives.ts
- modules/home/api/fetchLandingPageData.ts
- modules/tags/constants/poll-tags-mapping.json
- pages/api/cache/info.ts
- pages/api/executive/index.ts
- pages/dashboard/index.tsx
Prior to this, we were only clearing the cache key for github executives.
This did not clear the proposals cache key, so exec lists stayed the same.
> Exec cache

- modules/polling/components/ChoiceSummary.tsx
- modules/polling/components/PollOverviewCard.tsx
- modules/polling/components/poll-vote-input/QuickVote.tsx
- pages/polling/review.tsx
If you voted on a poll, and then tried to vote again (MOBILE), the edit choice button would not show up
> Fix vote edit

- pages/api/polling/vote.ts
If you include skipDiscord in the request, discord won't be notified of the error.  This way TechOps can run a test that makes sure error messages are properly returned from the vote api without spamming our discord.
> allow for skipping discord error message in vote api

- pages/api/polling/vote.ts
Use ethers util to get signature values
https://docs.ethers.io/v5/api/utils/bytes/#utils-splitSignature
> Handle relay tx error

- cypress/integration/account.spec.ts
- cypress/integration/esmodule.spec.ts
- modules/executive/components/VoteModal/DefaultView.tsx
- modules/executive/components/VoteModal/index.tsx
- modules/polling/components/poll-vote-input/SingleSelect.tsx
- modules/polling/components/review/ReviewBox.tsx
- pages/account.tsx
- pages/address/[address]/index.tsx
- pages/polling/[poll-hash].tsx
> fix link to makermanual

- modules/polling/components/PollWinningOptionBox.tsx
> show default option on no participation polls

- modules/app/components/layout/Header.tsx
- pages/executive.tsx
Removes badge with counts on header
> Comment out badges and fetching

- pages/api/address/[address]/delegated-to.ts
- pages/api/delegates/index.ts
> go chat gpt

- lib/config.ts
- modules/app/client/analytics/AnalyticsContext.tsx
- modules/app/components/layout/Head.tsx
- pages/_app.tsx
This PR fixes the console errors related to content prefetching and Content Security Policy and potentially the MetaMask error on Firefox for the vote.makerdao.com domain. See these messages for context:
https://discord.com/channels/836646301986848768/1070721828546433058/1077865668474576936
https://discord.com/channels/836646301986848768/869616783936593990/1080196250403622912
> Content security policy errors

- modules/web3/constants/networks.ts
Updates to use the staging db in `preview` and `development` (i.e. our staging) environments in vercel
> Try NEXT_PUBLIC_VERCEL_ENV

- lib/github/index.ts
- modules/delegates/api/fetchDelegates.ts
- modules/delegates/api/fetchGithubDelegates.ts
- modules/delegates/api/getDelegatesRepositoryInfo.ts
- package.json
- pages/executive/create.tsx
Fetch all the delegates information from the aggregated json
> Fetch delegatedata aggregated

- modules/app/components/Tabs.tsx
Found an error caused by the Tabs component affecting both local and production environments. Read these messages for context and references: https://discord.com/channels/836646301986848768/854643254741565450/1100528454421713026
> Fix Tabs component routing in React 18

- modules/executive/api/fetchExecutiveVoteTally.ts
- pages/executive/[proposal-id].tsx
> fix exec responsivenes

- modules/cache/constants/cache-keys.ts
- modules/polling/components/ShareVotesModal.tsx
- modules/polling/components/review/ReviewBox.tsx
- modules/polling/helpers/ballotIncludesAlreadyVoted.ts
- pages/api/polling/precheck.ts
- pages/api/polling/vote.ts
- pages/polling/review.tsx
It fixes the UI bug that allowed you to proceed to gasless voting without meeting the requirements.
> Fix vote proxy contract gasless error

- modules/mkr/components/MkrLiquiditySidebar.tsx
Fix the MKR in compound fetching function by applying the suggestion from Compound
> Fix compound MKR

- modules/polling/api/fetchPolls.ts
- modules/polling/types/poll.d.ts
Prevent filtering out of upcoming polls when caching active poll ids
> Prevent filtering out of upcoming polls

- modules/app/components/ResourceBox.tsx
> Update notion links

- pages/index.tsx
> cast combinedParticipation as a string

- modules/delegates/components/TopDelegates.tsx
~~seems like we need to merge master to develop, so pointing this to master for now to reduce diff. PR to merge master to develop: https://github.com/makerdao/governance-portal-v2/pull/824~~
> Show all avcs button

- modules/home/components/InformationParticipateMakerGovernance/InfoPoints.tsx
- modules/mkr/components/Deposit.tsx
Links to here: <https://dux.makerdao.network/how-to-create-a-vote-proxy-manually-using-etherscan>
> Update vote proxy guide

- modules/migration/delegateAddressLinks.ts
> Regenerative Finance AVC - PBG delegate link

- modules/migration/components/MigrationBanner.tsx
- modules/migration/components/MigrationInfo.tsx
- modules/migration/helpers/getMigrationBannerContent.ts
- modules/migration/hooks/useMigrationStatus.tsx
- pages/migration/delegate.tsx
- pages/migration/delegator.tsx
Update migration page with v2 delegate requirements
TODOs:
> Update migration page with v2 delegate requirements

- lib/theme/icons.js
- modules/app/components/layout/Header.tsx
- modules/app/components/layout/header/Banner.tsx
- modules/delegates/api/fetchDelegateAddresses.ts
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegates.ts
- modules/delegates/types/delegate.d.ts
- modules/gql/queries/allDelegates.ts
- modules/gql/queries/delegates.ts
- modules/home/components/Footer.tsx
- modules/home/data/bannerContent.json
- modules/migration/components/DelegateContractInfo.tsx
- modules/web3/constants/addresses.ts
- modules/web3/constants/chainID.ts
- pages/_app.tsx
- pages/migration/delegator.tsx
- playwright/forkVnet.ts
> update version querying and parsing

- modules/delegates/api/fetchDelegateAddresses.ts
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegates.ts
- modules/delegates/types/delegate.d.ts
- modules/migration/components/DelegateContractInfo.tsx
- pages/migration/delegator.tsx
- Renames version to delegateVersion
- Fixes delegate details page showing V1 for V2 delegates
> Rename version property to delegateVersion

- lib/theme/icons.js
- modules/address/components/AddressDelegatedTo.tsx
- modules/app/components/DateWithHover.tsx
- modules/app/components/layout/Header.tsx
- modules/app/components/layout/header/Banner.tsx
- modules/delegates/api/fetchDelegateAddresses.ts
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegates.ts
- modules/delegates/types/delegate.d.ts
- modules/gql/queries/allDelegates.ts
- modules/gql/queries/delegates.ts
- modules/home/components/Footer.tsx
- modules/home/data/bannerContent.json
- modules/migration/components/DelegateContractInfo.tsx
- modules/migration/helpers/expirationChecks.ts
- modules/migration/hooks/useMigrationStatus.tsx
- modules/web3/constants/addresses.ts
- modules/web3/constants/chainID.ts
- pages/_app.tsx
- pages/migration/delegator.tsx
- playwright/forkVnet.ts
> Apply version changes

- modules/address/components/AddressDelegatedTo.tsx
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegationEventsByAddresses.ts
- modules/delegates/components/DelegatedByAddress.tsx
- modules/delegates/components/modals/InputDelegateMkr.tsx
- modules/delegates/components/modals/UndelegateModal.tsx
- modules/delegates/helpers/formatDelegationHistory.ts
- modules/delegates/types/delegate.d.ts
- modules/gql/queries/subgraph/delegateHistoryArray.ts
- modules/gql/queries/subgraph/delegatorHistory.ts
> Show what's the source of the delegation

- modules/migration/hooks/useMigrationStatus.tsx
> Fix mkr delegated to v1 check in useMigrationStatus

- modules/contracts/eth-sdk.config.ts
> update v2 delegate factory address

- modules/gql/gql.constants.ts
> remove /private from the urls

- modules/contracts/eth-sdk.config.ts
- modules/delegates/components/DelegatesSystemInfo.tsx
> show v1 and v2 delegate factory in stats

- package.json
- yarn.lock
Uses resolutions to resolve elliptic to 6.6.1
> Use resolutions

- modules/app/components/layout/Header.tsx
- modules/web3/constants/networks.ts
- modules/web3/helpers/fetchGasPrice.ts
Gas being 0 gwei caused issues with 0 being evaluated as false. Now 0 shows as 0.xx. Also fixes link to the gas info site.
> Fix gas when gas is 0 gwei

- PULL_REQUEST_TEMPLATE.md
- modules/home/data/bannerContent.json
Deactivate Sky banner in bannerContent.json
> Deactivate Sky banner in bannerContent.json

- modules/polling/components/BallotBox.tsx
- package.json
- playwright.config.ts
- playwright/polling.spec.ts
- Added data-testid="review-ballot-button" to the Review & Submit Your Ballot button in BallotBox component
- Updated polling.spec.ts to use the new data-testid for more reliable button selection
- Added proper wait conditions in the test:
- waitFor({ state: 'attached' })
- waitForLoadState('networkidle')
- expect().toBeVisible()
- expect().toBeEnabled()
- added waitForLoadState
This change improves test reliability by using data-testid selectors and proper wait conditions instead of text-based selectors.
> test: fix polling spec test

- modules/web3/components/NetworkAlertModal.tsx
Adds the button to switch chains
> Add button to handle switching chains from an unsupported network

- modules/mkr/hooks/useFree.ts
- modules/mkr/hooks/useLock.ts
- modules/mkr/hooks/useOldChiefFree.ts
> Make the enabled parameter of contract writes more explicit

- package.json
- yarn.lock
> Dependabot43

- modules/delegates/api/fetchChainDelegates.ts
- modules/delegates/api/fetchDelegateAddresses.ts
- modules/delegates/api/fetchDelegatedTo.ts
- modules/delegates/api/fetchDelegates.ts
- modules/delegates/api/fetchDelegatesExecSupport.ts
- modules/delegates/api/fetchDelegationEventsByAddresses.ts
- modules/delegates/api/fetchDelegationMetrics.ts
- modules/executive/api/fetchExecutiveVoteTallyWithSubgraph.ts
- modules/gql/gql.constants.ts
- modules/gql/gqlRequest.ts
- modules/polling/api/fetchAllCurrentVotes.ts
- modules/polling/api/fetchPolls.ts
- modules/polling/api/fetchVotesByAddress.ts
- modules/polling/helpers/__tests__/parsePollMetadata.spec.ts
- modules/polling/helpers/parsePollMetadata.ts
- modules/polling/types/pollSubgraph.d.ts
- modules/tags/constants/poll-tags-mapping.json
- modules/web3/constants/networks.ts
- modules/web3/types/chain.d.ts
> delete some more unused spock code

- modules/wagmi/config/config.default.ts
maker portal PR: https://github.com/makerdao/governance-portal-v2/pull/1037
> Use multiInjectedProviderDiscovery, remove injected wallet (Sky)

- modules/wagmi/config/config.default.ts
-add wallet discovery to prod config
> add wallet discovery to prod config

- lib/theme/icons.tsx
Fixes Rabby icon by correcting the name
> Update icon name for Rabby Wallet

- modules/app/components/ErrorPage.tsx
- modules/app/components/ResourceBox.tsx
- modules/app/components/layout/Header.tsx
- modules/home/components/GovernanceStats.tsx
- modules/home/components/Participation.tsx
- modules/home/components/Stats.tsx
- modules/migration/components/ConnectWallet.tsx
- modules/migration/components/NewAddressError.tsx
- modules/migration/components/NewAddressInitial.tsx
- modules/migration/components/NewAddressSuccess.tsx
Link to the sky builders discord
> Update discord links and remove metrics dashboard link

- modules/polling/components/VoteBreakdown.tsx
> Sky develop -> main

- modules/wagmi/config/config.default.ts
- modules/web3/constants/networks.ts
TODO: update env var with the new rpc
Do we want to update the subgraph first before merging this?
> use new testnet

- modules/home/data/bannerContent.json
> Add active banner

- modules/app/components/layout/header/AppBanner.tsx
- modules/home/data/bannerContent.json
- pages/_app.tsx
Creates a banner to link to account page for creating a v3 delegate contract is Chief is not live yet
> Add delegate contract creation banner

- modules/contracts/contracts.ts
- modules/contracts/generated.ts
Update mainnet addresses for chief and vote delegate factory
> Mainnet addresses

- __tests__/pages/account.test.tsx
- Add test for votedForAddressZero state and UI
- Add test for isChiefLive state and UI
- Add tests for delegate contract address display
> unit test for voting address 0

- __tests__/pages/account.test.tsx
- modules/delegates/components/DelegateMKRChart.tsx
- pages/account.tsx
- fix disabled logic for create delegate button
- don't show alert and button about supporting the zero address if user already supports zero address
- fix decimal issue in chart y axis
> account page fixes

- playwright/forkVnet.ts
- playwright/shared.ts
update e2e vnet fork and test account
> update e2e fork id and test account

- modules/delegates/api/fetchGithubDelegates.ts
- modules/delegates/api/getDelegatesRepositoryInfo.ts
- modules/executive/api/fetchExecutives.ts
- modules/executive/executive.constants.ts
- modules/polling/api/fetchPolls.ts
- modules/polling/api/getPollTags.ts
- modules/polling/polling.constants.ts
- pages/executive.tsx
- scripts/fetchTags.mjs
* Updates metadata repo URLs
* Handles missing index files
> Metadata repo updates

- modules/executive/api/fetchExecutives.ts
- modules/executive/api/parseExecutive.ts
- modules/executive/executive.constants.ts
- Handle case where no active execs
- rename variables for urls to improve clarity
> Add support for tenderly executive propsoals

- package.json
- pages/api/address/[address]/delegated-to.ts
- pages/api/address/[address]/delegations.ts
- pages/api/address/stats.ts
- pages/api/delegates/[address]/info.ts
- pages/api/delegates/delegation-history/[address].ts
- pages/api/delegates/info.ts
- pages/api/executive/[proposal-id].ts
- pages/api/executive/all-locks.ts
- pages/api/executive/index.ts
- pages/api/executive/supporters.ts
- pages/api/polling/[poll-id-or-slug].ts
- pages/api/polling/tally/[poll-id].ts
- pages/api/polling/v2/active-poll-ids.ts
- pages/api/polling/v2/all-polls.ts
- pnpm-lock.yaml
* Updates swagger to v5
* Updates API docs to match latest code on endpoints
> Update API docs

- modules/home/components/ResourcesLanding/resources.ts
> Update relevant resources

- modules/app/components/PageLoadingPlaceholder.tsx
- modules/app/components/SkeletonThemed.tsx
- modules/delegates/components/TopDelegates.tsx
- modules/home/components/ResourcesLanding/resources.ts
- package.json
- pages/index.tsx
- pnpm-lock.yaml
* Fix formatting of large number in TopDelegates component
* Update resources in Resources section
* Remove unused code related to old landing page tabs nav
* Improve loading skeletons
Note: Ready for review, but waiting on a resource URL to add
> Misc fixes

- modules/polling/api/fetchVotesByAddress.ts
- playwright/delegates.spec.ts
- playwright/fixtures/delegate.ts
- playwright/fixtures/executive.ts
Get delegate and executive e2es passing.
The polling e2e doesn't recognize the address's sky balance, so didn't get that one working
The wallet e2e is flaky, it works for me locally but sometimes fails in ci.
> delegate and executives sky e2es

- modules/app/components/layout/header/Banner.tsx
- modules/home/data/bannerContent.json
> Update banner for interim text, fix wrapping

- modules/app/components/SkyUpgradeToastContent.tsx
- modules/app/hooks/useMigrationToast.tsx
> update migration toast bg and text color, and increase autoClose timeout

- modules/app/components/MkrUpgradeToastContent.tsx
> Finalize toast content

- modules/delegates/api/fetchDelegationEventsByAddresses.ts
- modules/delegates/helpers/formatDelegationHistoryChart.ts
- modules/gql/gql.constants.ts
- modules/gql/queries/subgraph/delegateHistoryArray.ts
- filter out staking engine delegations
- handle >100 delegations
- fix delegation chart accumulated total
> delegation history fixes

- modules/app/hooks/useMigrationToast.tsx
> update toast width on mobile

- modules/app/hooks/useMigrationToast.tsx
> Update mobile toast

- modules/polling/api/getPollTags.ts
Update poll tags file source to community repo file
> Update poll tags file

- modules/executive/api/analyzeSpell.ts
- pages/executive.tsx
> Return executive sky support value formatted

- modules/gql/gql.constants.ts
> update subgraph endpoints for legacy

- modules/delegates/api/fetchDelegates.ts
- modules/delegates/components/DelegateMKRDelegatedStats.tsx
- Update fetchDelegatesPaginated function to take in a includeExpired prop and edit the graphql query depending on it
- fix delegateVersion variable
- show 0 instead of Untracked if no mkr delegated
> delegate fixes

- .gitignore
- modules/home/api/fetchLandingPageData.ts
- pages/_app.tsx
- pages/api/sky/hat.ts
- pages/api/sky/polls.ts
- pages/index.tsx
- pages/polling.tsx
- playwright.config.ts
- playwright/executive.spec.ts
- playwright/fixtures/sky-executive.ts
- playwright/fixtures/sky-polling.ts
- playwright/forkVnet.ts
- playwright/helpers/depositMkr.ts
- playwright/legacy-polling.spec.ts
- playwright/polling.spec.ts
- playwright/shared.ts
> e2e: fix assertions

- pages/api/sky/executives/[proposal-id-or-key].ts
This PR introduces input validation for the proposal-id parameter on the /api/executive/[proposal-id] API endpoint. It ensures that the proposal-id is either a valid Ethereum address or a kebab-case string with a minimum length of three characters. Requests with an invalid format will now receive a 400 Bad Request error response. This resolves a TODO item to add validation for this parameter.
Test with a valid kebab-case ID:
Make an API call to /api/executive/my-test-proposal.
Expected: The API should respond with a 200 OK (or 404 Not Found if the proposal doesn't exist), but not a 400 error.
Test with a valid Ethereum address ID:
Make an API call to /api/executive/0xAb5801a7D398351b8bE11C439e05C5B3259aeC9B.
Expected: The API should respond with a 200 OK (or 404 Not Found), but not a 400 …
> validate the proposal id
