__tests__/lib/api.ts
components/PollCreateModal.tsx
lib/api.ts
lib/polling/validator.ts
pages/polling/create.tsx

Executive improvements:
https://app.clubhouse.io/dux-makerdao/story/47/create-executive-ui-whitelisted-to-governance-facilitators-load-from-markdown-in-github
Polling improvements: https://app.clubhouse.io/dux-makerdao/story/48/create-poll-ui-refresh-whitelisted-to-governance-facilitators-load-from-markdown-in-github
1. Ignore executive votes with invalid address and invalid dates.
2. Improves formatting in the polling/create page
Polling changes:
1. Go to the /polling/create page.  input a url pointing to a poll, e.g. https://raw.githubusercontent.com/makerdao/community/master/governance/polls/MIP9%20Community%20Greenlight%20Poll%20-%200xBTC%20-%20July%205%2C%202021.md
2. Confirm that it still displays poll info correctly, but improves formatting of options and content markdown, and …

Exec cms and poll create fixes

---

components/executive/ExecutiveOverviewCard.tsx
lib/utils.ts

Fixes issue that was brought up in Rocket Chat (confirmed desired fix with LFW):
Removes timestamp from executive posted date on overview card (instead of showing `0:00 UTC` for all)
1. Go to `/executive`
2. See that the posted date on each card no longer shows the timestamp
Before:
After:

Remove time from executive posted date

---

components/executive/ExecutiveOverviewCard.tsx
lib/executive/getStatusText.ts
pages/executive/[proposal-id].tsx

n/a
Fixes an issue where we weren't showing that an executive had been previously executed.
Refactors status logic that was being used in multiple places into a single helper.
1. Go to `/executive`
2. Scroll down to the Dec 11 exec (governing proposal)
3. Verify it now shows when it was executed
Before:
After:

Fix exec status issue and refactor into helper

---

README.md
components/delegations/DelegateCard.tsx
components/delegations/DelegateDetail.tsx
components/delegations/modals/Confirm.tsx
lib/api.ts
lib/delegates/fetchChainDelegates.ts
lib/delegates/fetchDelegates.ts
lib/delegates/fetchGithubDelegates.ts
lib/delegates/getDelegatesRepositoryInfo.ts
lib/fscache/index.ts
lib/maker/index.ts
lib/maker/web3react/hooks.ts
lib/theme.js
pages/api/delegates/[address].ts
pages/api/delegates/index.ts
pages/delegates/[address].tsx
pages/delegates/[network]/[address].tsx
pages/delegates/index.tsx
types/delegate.d.ts

- Fetches kovan delegates from https://github.com/makerdao-dux/voting-delegates
- Fetches kovan and mainnet delegates from serverside paths. Disabling clientside fetching and minimizing the number of requests.
- Remove last voted date 
- ⚠️ Introduces `getMaker(network)` that returns a instance of maker for the specified network. This is usefull to fetch server side kovan information
- Adds styles for tables for markdown rendering as suggested by @LongForWisdom
- Separate FScache into a module, add expiration date
- Fetch delegates through API requests on client side (with the cache included)
1. Go to delegates page in kovan
2. See a recognized delegate and can access to their profile
1. See that http://localhost:3000/api/delegates?network=kovan works
2. See that …

refactor delegations fetching

---

components/delegations/DelegateDetail.tsx
lib/delegates/fetchDelegates.ts
types/delegate.d.ts

Links to the external URL provided by the delegates page. 
1. Go to delegates detail and see the link to the external profile
2. It should pick the information from here https://github.com/makerdao-dux/voting-delegates/tree/main/delegates/0xc8829647c8e4131a01354ccac993388568d12d00

feat: Represent link to external profile

---

components/delegations/DelegateCard.tsx
components/delegations/DelegatePicture.tsx
lib/common/shuffleArray.ts
lib/delegates/constants.ts
lib/delegates/fetchDelegates.ts
lib/theme.js
pages/delegates/index.tsx
types/delegate.d.ts

https://app.clubhouse.io/dux-makerdao/story/326/randomize-order-of-delegates
https://app.clubhouse.io/dux-makerdao/story/327/emphasize-border-of-delegate-card-if-owner
Adds emphasis to a delegate card if the connected account is the owner
Randomizes the order of the recognized and shadow delegates sections
1. Go to `/delegates` with a user that owns a delegate contract
2. Ensure that border shows emphasis
3. Ensure the order of the delegates in each section is randomized each time the page loads
-

Delegate list updates

---

components/delegations/DelegateCard.tsx
lib/analytics.ts
lib/config.ts
lib/constants.ts
lib/hooks/index.ts
lib/hooks/useAnalytics.ts

https://app.clubhouse.io/dux-makerdao/story/201/mixpanel-configuration
- Adds a custom hook to make mixpanel tracking easier/cleaner.
- Add new API keys to the ENV and remove the old ones from the codebase.
1. Click some buttons
2. Go to mixpanel dashboard and see that your clicks were tracked.

add hook for mixpanel tracking, use in delegates.tsx

---

components/delegations/DelegateDetail.tsx

https://app.clubhouse.io/dux-makerdao/story/369/fix-spacing-for-see-external-profile-on-delegate-page
Fix spacing of 'see external profile'

move 'see external profile' to right side

---

components/delegations/DelegateDetail.tsx

https://app.clubhouse.io/dux-makerdao/story/372/don-t-truncate-middle-of-delegate-address-on-profile-detail-page
Before:
After:

Remove truncation of address on profile page

---

README.md
lib/client/analytics/AnalyticsContext.tsx
lib/client/analytics/mixPanel.ts

Fixes issue where app crashes if `NEXT_PUBLIC_MIXPANEL_DEV` and/or `NEXT_PUBLIC_MIXPANEL_PROD` don't exist in the `.env`
Also adds these configs to the README
On develop branch, attempt to run app without `NEXT_PUBLIC_MIXPANEL_DEV`. App will crash. Then try the same but on this branch. App should not crash.

Add mixpanel config check

---

pages/executive/[proposal-id].tsx

https://app.clubhouse.io/dux-makerdao/story/401/error-fetching-on-chain-effects
Hides on-chain effects tab since we know it will error everytime until the (third party) API is updated.
Also adds error handling for the comments tab so that it doesn't perpetually say "loading" if there is an issue fetching comments.
Go to an executive proposal. See that the tab no longer exists.

Hide on-chain effects, add comments fetch error handling

---

modules/delegates/components/DelegatePicture.tsx
modules/executives/components/CurrentlySupportingExecutive.tsx
modules/polls/components/PollVoteHistoryItem.tsx
modules/polls/components/VotesByAddress.tsx

- It adds the ranked label 
- makes delegate image round and better on phone

fix: add ranked label and make image round

---

lib/abis/voteProxyAbi.json
lib/maker/index.ts
modules/address/components/AddressDetail.tsx
modules/address/types/addressApiResponse.d.ts
modules/polls/api/fetchAddressPollVoteHistory.ts
pages/address/[address]/index.tsx
pages/api/address/[address]/index.ts

Currently, the vote breakdown lists the proxy address as the voter
If you click the proxy address, there's no history to show (we don't query for it in spock)
This adds a check to see if the address is a proxy contract before fetching history. If it is, it fetches the history for the hot wallet.
We might want to move this logic to spock instead. We should also consider how we want to convey this info in the UI.

Check if address is a proxy contract

---

pages/executive/[proposal-id].tsx

hide scrollbar in exec supporters

---

components/Tabs.tsx

https://app.shortcut.com/dux-makerdao/story/528/fix-jumping-vote-detail-vote-breakdown-buttons
Fix jumping tab buttons
Go to `/polling/QmUAXKm4?network=mainnet#vote-breakdown` and refresh the page
See that the "Poll Detail" and "Vote Breakdown" buttons no longer jump around.

Fix jumping buttons

---

modules/address/components/AddressDetail.tsx
modules/polling/components/PollVoteHistoryItem.tsx
modules/polling/components/PollVoteHistoryList.tsx

https://app.shortcut.com/dux-makerdao/story/525/change-vote-breakdown-popup-hover-behaviour
https://app.shortcut.com/dux-makerdao/story/532/vertically-align-proxy-contract-label-with-address
Remove breakdown tooltip on vote history item
Aligns proxy contract text for vote history list
Go to `/address/0xd8bba030ae1b52a5e45f5cf05de47dcbb3a1dfc4?network=mainnet`
See that proxy contract text is now aligned and that vote history no longer has a tooltip hover

Remove breakdown tooltip + align proxy text

---

components/es/burnModal/Default.tsx

https://app.shortcut.com/dux-makerdao/story/506/fix-cancel-button-in-the-warning-pop-up-of-esm
Fix cancel button that doesn't work
1. Go to `/esmodule`
2. Click burn MKR 
3. Then click cancel button
4. Make sure modal closes.

Fix cancel button in ES modal

---

modules/delegates/components/DelegateCard.tsx
modules/delegates/components/DelegateContractExpiration.tsx
modules/delegates/components/DelegateDetail.tsx
modules/delegates/components/DelegateLastVoted.tsx
modules/delegates/components/index.ts

https://app.shortcut.com/dux-makerdao/story/276/add-last-voted-value-to-delegate-list-card
Adds last voted data to delegate detail view
Go to delegate detail
See the last voted data

Add last voted to delegate detail

---

components/executive/Withdraw.tsx
lib/theme.js
modules/delegates/components/modals/DelegateModal.tsx
modules/delegates/components/modals/InputDelegateMkr.tsx
modules/delegates/components/modals/UndelegateModal.tsx

https://app.shortcut.com/dux-makerdao/story/371/alert-users-they-need-to-withdraw-mkr-from-chief-to-delegate-it
Allows a user to easily withdraw MKR from chief before depositing into a delegate contract.
Also two bug fixes:
1. Show the correct MKR balance in the chief withdrawal modal for users with a delegate contract.
1. disable button when inputting a number larger than your MKR balance in delegate deposit and chief withdraw modals.
started adding a new yellow-colored alert, but instead just using the orange 'notice' one.

Delegate modal alert

---

.circleci/config.yml
package.json
yarn.lock

Fix CI.  Sentry was halting ci with this error: "Could not find the SHA of the previous release in the git history. If you limit the clone depth, try to increase it. Otherwise, it means that the commit we are looking for was amended or squashed and cannot be retrieved. Use --ignore-missing flag to skip it and create a new release with the default commits count."
This PR just adds the --ignore-missing flag.
Another option could be to integrate sentry directly with Github.  Not sure if that would prevent this issue, but we do also get this message in CI: "Could not determine any commits to be associated with a repo-based integration. Proceeding to find commits from local git tree."  I don't have owner permissions in the github repo though.

Debug sentry

---

pages/api/executive/analyze-spell/[address].ts

Fix mistake where the `eta` variable is actually `nextCastTime` and vice versa.
testing this requires having a spell with office hours that has passed but not yet been executed...

Office hours fix

---

pages/polling/[poll-hash].tsx

https://app.shortcut.com/dux-makerdao/story/678/remove-winning-option-badges-for-polls
Replace results badge with text design
Go to an ended poll. See design updates.

Replace results badge with text design

---

__tests__/lib/polling/validator.spec.ts
modules/polling/helpers/validator.ts
yarn.lock

https://app.shortcut.com/dux-makerdao/story/481/update-categories-in-the-validator-function-for-when-polls-are-created
When validating poll markdown (`polling/create`), this update will now fetch categories dynamically from the community repo. If it fails, it will fallback to the hardcoded categories we have been relying on.
Go to `polling/create`, ensure validation works

Add fetch for categories json on validation

---

.circleci/config.yml
modules/executive/components/ExecutiveOverviewCard.tsx
modules/executive/helpers/getStatusText.ts
modules/executive/hooks/useMkrOnHat.ts
pages/executive/[proposal-id].tsx

https://app.shortcut.com/dux-makerdao/story/661/add-visual-for-how-many-mkr-needed-to-pass-vote-for-executives
Adds additional status information including if exec has expired or how much additional MKR is needed to pass
1. Go to exec page, see new statuses (hard to recreate the additional MKR one if you don't have an exec that is active and hasn't passed)

Feature/sc 661/add visual for how many mkr needed to pass

---

modules/executive/components/SpellEffectsTab.tsx

https://app.shortcut.com/dux-makerdao/story/666/improve-loading-animation-for-spell-detail-tab
Updates loading state for spell data
1. Go to spell detail tab for an executive
2. Observe new loading state
Loading:
Loaded:

Update spell data loading state

---

modules/delegates/components/DelegatePicture.tsx

https://app.shortcut.com/dux-makerdao/story/748/add-jazzicons-to-shadow-delegates
Add jazzicons for shadow delegates
1. Go to delegates page
2. See jazzicons for shadow delegates ✨

Add jazzicons for shadow delegates

---

modules/delegates/components/DelegateCard.tsx

https://app.shortcut.com/dux-makerdao/story/667/make-own-shadow-delegate-contract-more-prominent-on-delegates-page
Adds an owner badge to delegates if the connected wallet is an owner
1. Go to delegates page
2. Connect to a wallet that owns a delegate contract
3. See badge ✨

Feature/sc 667/make own shadow delegate contract more prominent

---

modules/polling/api/parsePollMetadata.ts

https://app.shortcut.com/dux-makerdao/story/344/better-handle-two-polls-having-the-same-hash
If two polls have the same hash, remove the older poll when deduplicating.  The impetus for this is that one time a poll was submitted with either the start or end date wrong (I forget which), so a new one was submitted and it had the same multihash.  But the frontend would dedupe by deleting the 2nd poll, causing issues.  Since then we've changed the way poll hashes are created to include the entire poll document (including the frontmatter) when creating the hash, so we _shouldn't_ run into this situation again where two polls have the same hash, because changing the start/end date would cause the hash to change.  But better safe than sorry.
On goerli I added a poll so that there are two polls …

ensure we always remove older polls when deduping polls

---

modules/app/components/layout/header/AccountSelect.tsx

https://app.shortcut.com/dux-makerdao/story/550/trezor-wallet-not-working-on-latest-deployment
Loads 25 addresses instead of 10 for hardware wallets, and shows them over 5 pages of 5 addresses, rather than one large modal with 10 addresses
Connect a hardware wallet, try selecting an address not on the first page.

add hw address pagination

---

pages/executive/[proposal-id].tsx

https://app.shortcut.com/dux-makerdao/story/239/0-supporters-message-executive
Show 0 supporters message if there are no supporters
Go to executive detail without supporters or change the api to return 0

feat: Show 0 supporterts

---

lib/validators/email.ts
modules/executive/api/parseExecutive.ts

updates the matcher that remove the "Template - [..." string from proposal titles
Old:
New:

add a new string to edit title matcher

---

modules/delegates/components/ManageDelegation.tsx
pages/address/[address]/index.tsx

https://app.shortcut.com/dux-makerdao/story/797/add-delegate-undelegate-buttons-on-delegate-profile-page
Adds delegate quick actions to delegate detail
Go to delegate detail, press buttons, profit

Add delegate actions to delegate detail

---

modules/delegates/components/DelegatesSystemInfo.tsx
modules/mkr/hooks/useTotalMkr.ts

https://app.shortcut.com/dux-makerdao/story/536/add-of-total-mkr-tokens-delegated-to-delegates-system-info
shows percent of total supply of MKR delegated
go to delegates page and see the %

Show percentage of MKR delegated

---

modules/executive/components/DateFilter.tsx
modules/polling/api/fetchPolls.ts
modules/polling/components/DateFilter.tsx
pages/polling.tsx

https://app.shortcut.com/dux-makerdao/story/551/poll-date-filter-filter-on-end-date-instead-of-creation-date
Changes text and filters in poll page 
Try filters on poll page, see if they make sense

Fix polling date filter issue

---

lib/theme.js
modules/delegates/api/fetchDelegationHistory.ts
modules/delegates/api/fetchMKRWeightHistory.ts
modules/delegates/components/DelegateDetail.tsx
modules/delegates/components/DelegateMKRChart.tsx
modules/delegates/components/DelegateVoteHistory.tsx
modules/delegates/components/DelegatedByAddress.tsx
modules/delegates/types/delegate.d.ts
modules/delegates/types/delegatesAPI.d.ts
pages/address/[address]/index.tsx
pages/api/delegates/delegation-history/[address].ts

https://app.shortcut.com/dux-makerdao/story/625/add-list-of-delegators-to-delegate-profile-page
Shows a table of delegators who have delegated to a delegate.
1. go to a delegate page and see the table
2. find a delegate with 0 MKR and don't see the table

fetch delegator data in API

---

modules/app/components/VideoModal.tsx
modules/app/components/layout/Head.tsx
pages/index.tsx

https://app.shortcut.com/dux-makerdao/story/847/add-how-to-vote-button-with-vimeo-embed-to-homepage
adds a video on how to vote on the home page 
Go to the home page, click on "how to vote" see video poping

Add video modal home

---

modules/app/components/VideoModal.tsx

https://app.shortcut.com/dux-makerdao/story/878/disable-round-bottom-corners-for-how-to-vote-video-overlay
Fixes border radius on how to vote video modal
1. Open the "how to vote" modal
2. See updates ✨

Remove round corners on video modal

---

lib/datetime.ts
lib/utils.ts
modules/delegates/api/fetchMKRWeightHistory.ts
modules/delegates/components/DelegateMKRChart.tsx

https://app.shortcut.com/dux-makerdao/story/876/mkr-delegate-weight-chart-dates-on-chart-don-t-always-line-up-with-dates-on-the-delegation-history-table
Handle situation where there are multiple transactions in a single day, selecting the most recent one which will have the correct lockTotal.
Open the metrics tab and compare the delegation history table with the MKR weight chart and verify that the dates on the chart and the table line up.
**Before:**
**After:**

account for multiple txs on same day

---

modules/polling/components/ChoiceSummary.tsx
modules/polling/components/PollOverviewCard.tsx
modules/polling/components/RankedChoiceSelect.tsx
modules/polling/components/SingleSelect.tsx
pages/polling.tsx
pages/polling/review.tsx

https://app.shortcut.com/dux-makerdao/story/803/show-current-poll-vote-option-on-mobile
Updates the mobile voting experience to match desktop
1. On mobile sized screen, go to `polling` page
2. Connect wallet
3. Attempt to vote

Feature/sc 803/show current poll vote option on mobile

---

modules/delegates/api/fetchDelegationHistory.ts
modules/delegates/components/DelegateDetail.tsx
modules/delegates/components/DelegateMKRDelegatedStats.tsx

https://app.shortcut.com/dux-makerdao/story/913/add-of-delegating-addresses-to-delegate-detail-page
add total active delegators to delegate detail page status bar

show active delegators count in delegate detail page

---

modules/app/components/Tabs.tsx
modules/comments/components/CommentItem.tsx
modules/executive/components/ExecutiveOverviewCard.tsx
modules/polling/components/PollOverviewCard.tsx
pages/executive/[proposal-id].tsx
pages/polling/[poll-hash].tsx

Link to comments tab from comment count component.
Doesn't work for executives now since the entire executive card is clickable. So clicking it for an exec will still take you to the poll-detail tab.
Made a change to the Tabs component so the slug for the comments tab ends in #comments (instead of .e.g. #comments-4)
Also minor formatting improvement for comments on ranked choice polls.
On preview deployment, click on a comment count from either the home page or polling page.

Comments link

---

__tests__/pages/polling.spec.tsx

https://app.shortcut.com/dux-makerdao/story/981/add-test-to-polling-page-make-sure-ballot-doesn-t-show-when-no-account-connected
Add test for testing state with and without account connected

Add test for testing state with and without account connected

---

modules/comments/components/CommentItem.tsx
modules/comments/components/ExecutiveComments.tsx
modules/comments/hooks/useExecutiveComments.ts
modules/comments/types/comments.d.ts

The UI showed NaN in the voter weight of an executive comment when the weight was >1000 because the db would return commas in the string representation of the numbers, which caused an error when converting them to BigNumbers.
This PR converts the voterWeight from a string to a bigNumber, minding the commas, in the useExecutiveComments hook.
Poll comments use type BigNumber for the voterWeight variable, so this reduces differences between the exec comments and poll comments types used by the components.
To test:
Pantera's vote weight is shown here: https://governance-portal-v2-fpiwhy0pj-dux-core-unit.vercel.app/executive/template-executive-vote-offboarding-usdt-collateral-core-unit-budget-distributions-october-1-2021?network=mainnet#comments
but not on production: …

convert voterWeight to BigNumber in useExecutiveComments hook

---

modules/address/components/AddressIcon.tsx
modules/address/components/AddressIconBox.tsx
modules/app/components/layout/header/AccountBox.tsx
modules/delegates/components/DelegateDetail.tsx
modules/delegates/components/DelegatePicture.tsx
modules/web3/components/ConnectWalletButton.tsx
package.json
yarn.lock

Show user ens avatar if already had, else fallbacks to jazzicon
Places to test:
- Connect Button
- Account Popup
- Delegate card
- Delegate detail
Replaced `@ukstv/jazzicon-react` packaged with `@davatar/react`

feat: ens avatar support

---

next.config.js
pages/_middleware.ts
pages/api-docs/index.tsx

Fix vulnerability query HTML injection can be done to swagger through query parameters. Force the user to access the route without query parameters. 
Added a middleware https://nextjs.org/docs/middleware that redirects any request with query parameters to non query parameters

Remove query parameters on api docs

---

modules/delegates/api/fetchDelegates.ts
modules/executive/api/analyzeSpell.ts
modules/executive/api/fetchExecutives.ts
modules/executive/components/ExecutiveOverviewCard.tsx
modules/executive/types/proposal.d.ts
modules/executive/types/spellData.d.ts
modules/home/components/ExecutiveIndicator.tsx
pages/api/executive/index.ts
pages/delegates/index.tsx
pages/executive.tsx
pages/executive/[proposal-id].tsx
pages/index.tsx

- We trying to fetch the spell data for the executives on the backend, because it was failing to load the executives page (big FE query that blocks the following requests)
We moved it to the backend, so the executives come with some of the spell data 
Why? 
Is used on the frontend by several components:
- sorting all the executives by MKR
- executive indicator uses all the proposals that have been scheduled 
The problem is that fetching all the spellData on the backend is blocking now the serverside rendering/static generation on the build, it takes a lot of time to do for all the executives.
This is a problem that will scalate over time, the more executives, the worse it gets.
- I'm adding a pagination to fetch 0-20 executives on the first load, and then allow the user to fetch more
Our …

Adding pagination

---

modules/delegates/api/fetchMKRWeightHistory.ts

In the MKR delegate graph, properly account for events that are in a different calendar year
View Flip Flap Flop's MKR weight over time graph.  It should show that it drops to ~17K, since that how much he has delegated to him now. Whereas production still shows ~30K.

account for dates in a different year in mkr delegation graph

---

modules/polling/api/fetchTallyPlurality.ts

https://app.shortcut.com/dux-makerdao/story/1045/if-abstain-is-the-only-vote-there-is-an-error
Fix error that occurs if abstain is only vote in a poll
Go to `/polling`, see latest poll added (all the way at bottom) has only abstain vote in it. No error occurs anymore.

Add check to see if abstain is the only vote

---

modules/polling/components/PollOverviewCard.tsx
modules/polling/components/VoteBreakdown.tsx

https://app.shortcut.com/dux-makerdao/story/818/add-ranked-choice-poll-indicator-to-vote-breakdown
Add ranked-choice indicator to vote breakdown
Add ranked-choice indicator to poll overview
Go to `http://localhost:3000/polling/QmYj6Wzd#vote-breakdown` and see indicator

Add ranked choice indicator, fix mobile displays

---

lib/string.ts
lib/theme.js
modules/address/components/AddressDelegatedTo.tsx
modules/address/components/AddressMKRDelegatedStats.tsx
modules/app/components/SystemStatsSidebar.tsx
modules/delegates/components/DelegateCard.tsx
modules/delegates/components/DelegateMKRDelegatedStats.tsx
modules/delegates/components/DelegatedByAddress.tsx
modules/delegates/components/DelegatesSystemInfo.tsx
modules/esm/components/ProgressRing.tsx
modules/esm/components/ShutdownModal.tsx
modules/executive/components/ExecutiveOverviewCard.tsx
modules/executive/helpers/getStatusText.ts
modules/home/components/SystemStats.tsx
modules/mkr/components/MKRInput.tsx
modules/mkr/components/MkrLiquiditySidebar.tsx
modules/polling/components/VoteBreakdown.tsx
modules/polling/components/VotesByAddress.tsx
pages/executive/[proposal-id].tsx

> 2 decimals whenever an MKR value is displayed (except for >999) and we want 6 decimals for inputs (eg delegate/u delegate and deposit/withdraw)

use new rules for decimal places

---

modules/home/components/PollCategoriesLanding.tsx
modules/polling/components/PollCategoryTag.tsx
modules/polling/components/PollOverviewCard.tsx
pages/polling.tsx

Adds URL params for poll categories
Makes poll tags on landing page links

Polling url param

---

modules/executive/api/fetchMkrInChief.ts
modules/executive/api/fetchMkrOnHat.ts
modules/home/components/GovernanceStats.tsx
pages/index.tsx

Moves mkr in chief and mkr in hat fetching to static props
This gets rid of some initial loading state on the home page and removes the page shifting

Refactor stats fetching to static props

---

modules/home/components/TabsNavigation.tsx

Makes the active and hover bottom border of the subheader the primary color

make subheader active item border green

---

modules/polling/components/QuickVote.tsx

If editing a vote option on review page, don't overwrite comments. Use ballot `update` function instead of `add`.

Update vote instead of add if editing

---

modules/app/helpers/getVoteProxyAddresses.ts
modules/comments/components/PollCommentItem.tsx
modules/delegates/hooks/useDelegateAddressMap.ts
modules/polling/components/PollOverviewCard.tsx
modules/polling/components/PollVoteHistoryItem.tsx
modules/polling/components/QuickVote.tsx
modules/polling/components/RankedChoiceVoteSummary.tsx
modules/polling/components/VoteWeightVisual.tsx
modules/polling/components/VotesByAddress.tsx
modules/polling/helpers/getVoteColor.ts
pages/polling/review.tsx

Hotfix includes:
[Increase refresh interval for delegate mapping, cache proxy info](https://github.com/makerdao/governance-portal-v2/pull/513/commits/703cc426f31f73f4cb76174332606e56848a25cc)
[Update vote instead of add if editing](https://github.com/makerdao/governance-portal-v2/pull/513/commits/c9be57f7ada7602863b61955fccff6ad6ec207cb)
[display ranked choices](https://github.com/makerdao/governance-portal-v2/pull/513/commits/7dfa8048618cab6ff25d19dee9fd354a2de6e9c4)
[Add margin on poll cards on review page](https://github.com/makerdao/governance-portal-v2/pull/513/commits/626fa89a9f73cbca6bd0bd92aee51c6a3bfa06b2)
[Add margin on votes by address](https://github.com/makerdao/governance-portal-v2/pull/513/commits/32401b16728b83ca05ca8ba426bc17ae6ed6d771)
---
Original PR:
Fixes voter …

use grey for ranked choice voter visual

---

lib/cache.ts
modules/polling/context/BallotContext.tsx
modules/polling/helpers/getPollTally.ts
modules/polling/helpers/utils.ts
pages/api/polling/tally/[poll-id].ts
pages/api/polling/tally/[poll-id]/invalidate-cache.ts

Reduce TTL of poll tally to 5 mins, if poll is expired leave it to 1 day.
Add endpoint to invalidate cache for tally, call it after voting:
PS: invalidating cache after voting won't do much because spock didn't ingest the data yet, so a future request to the tally will still bring innacurate results, but at least it will include the new tally with only 5 mins ttl

invalidate cache and reduce ttl tally

---

modules/delegates/components/DelegateMKRDelegatedStats.tsx
modules/delegates/components/DelegateOverviewCard.tsx

As discussed in discord, this removes "MKR delegated by you" stats from the delegate overview card and delegate detail header when there is no account connected. This frees up some space and removes redundant information (MKR delegated by you is always 0 when no account is connected).

Only show MKR delegated by account when account is connected

---

pages/index.tsx

Fixes hook render warning on goerli by moving the hook to the top of the component

move hook to top of the component 🧠

---

lib/theme/markdown.js

text in `pre` doesn't wrap by default, so add a style to our markdown theme to wrap long code text.
Before:
After:

make pre > code text wrap in markdown

---

modules/delegates/api/fetchDelegates.ts

don't count expired or duplicate delegates in stats 
OLD
NEW

exclude expired and duplicate delegates in stats

---

lib/theme/forms.js
modules/delegates/components/filters/DelegatesShowExpiredFilter.tsx
modules/delegates/components/filters/DelegatesStatusFilter.tsx
modules/delegates/components/filters/DelegatesTagFilter.tsx
modules/delegates/helpers/filterDelegates.ts
modules/delegates/stores/delegatesFiltersStore.ts
pages/delegates/index.tsx

https://app.shortcut.com/dux-makerdao/story/1618/add-show-expired-delegates-button-as-replacement-for-expired-delegates-filter-option
Move expired delegates out of status filter and add checkbox filter
Go to delegates page and test out expired delegates checkbox

Move expired delegates out of status filter and add checkbox filter

---

modules/delegates/components/DelegateAvatarName.tsx
modules/delegates/components/DelegateAvatarNameLight.tsx
modules/delegates/components/DelegatePicture.tsx
modules/delegates/components/TopDelegates.tsx
modules/home/components/Participation.tsx

Gets rid of double-wrapping of avatar + name with InternalLink and removes the console warning seen below

Fix double link wrapping of avatar + name

---

modules/polling/components/PollOverviewCard/PollVoteTypeIndicator.tsx
modules/tags/constants/poll-tags-mapping.json

Update tooltips to prevent text overflow out of the screen / off of the page
Before:
After:

prevent tooltip text overflow

---

lib/config.ts
modules/delegates/api/fetchChainDelegates.ts
modules/delegates/api/fetchDelegates.ts
modules/delegates/hooks/useVoteDelegateAddress.ts
modules/web3/helpers/getContracts.ts
modules/web3/helpers/getReadOnlyContracts.ts
modules/web3/hooks/useContracts.ts
next.config.js

- Removes the custom alchemy api key for delegates and drastically simplifies `getContracts`.
- Fixes a bug where the signer was getting cached in an unintended way, causing an issue when switching accounts.
The custom apiKey was intended to help us separate and identify specific calls to delegate contracts in order to learn more about our Alchemy usage. Ultimately this method was kind of shoe-horned in, and only complicated things when we refactored `getContracts` into a singleton.
Probably an even better way to get granular data about our Alchemy usage and contract calls is to use a new Axiom library [next-axiom](https://github.com/axiomhq/next-axiom). Here we can add logging after the calls are made sending data to alchemy about the RPC call, and later do some data analytics.

deprecate the custom apiKey in get contracts fixing wrong signer bug

---

codegen.yml
graphql.schema.json
modules/delegates/api/fetchDelegatedTo.ts
modules/delegates/api/fetchDelegates.ts
modules/delegates/api/fetchDelegationEventsByAddresses.ts
modules/delegates/helpers/formatDelegationHistory.ts
modules/delegates/types/delegate.d.ts
modules/gql/generated/graphql.tsx
modules/gql/queries/mkrDelegatedTo.ts
modules/gql/queries/mkrLockedDelegateArray.ts

Updates delegate events, to use the msg.sender as the delegator address, instead of the tx.origin
To test, compare delegation events on production to the deployment here: https://governance-portal-v2-git-updateddelegatequeries-dux-core-unit.vercel.app/
Also look at Rune’s Gnosis safe delegation history:
https://governance-portal-v2-git-updateddelegatequeries-dux-core-unit.vercel.app/address/0xf65475e74c1ed6d004d5240b06e3088724dfda5d#account-details compared to production: https://vote.makerdao.com/address/0xc0583df0d10c2e87ae1873b728a0bda04d8b660c#account-details
And as we can see here^, we’re currently missing Rune’s 5000 un-delegation event from Hasu.  That’s why production shows that someone delegated -5000 MKR to Hasu: https://vote.makerdao.com/address/0xafaff1a605c373b43727136c995d21a …

Updated delegate queries

---

modules/comments/api/getPollComments.ts
modules/comments/types/comments.ts
pages/api/comments/polling/add.ts

Changes to get and add comments in gasless , it puts a property on the comment object indicating that is gasless, but it mantains the origin network.

Refactoring api for comments on gasless

---

modules/app/context/AccountContext.tsx
modules/delegates/components/modals/InputDelegateMkr.tsx
modules/executive/components/VoteModal/DefaultView.tsx
modules/executive/hooks/useVotedProposals.ts
modules/mkr/components/Deposit.tsx
modules/mkr/components/Withdraw.tsx
modules/mkr/hooks/useLockedMkr.ts
modules/polling/context/BallotContext.tsx
pages/account.tsx
pages/api/polling/precheck.ts
pages/custom-spell/[address].tsx
pages/custom-spell/index.tsx
pages/executive.tsx
pages/index.tsx
pages/polling.tsx
pages/polling/review.tsx

We had duplicated code that checked which was the right account to use for voting, i removed it and added to the "useACcount" hook, so we can just access the right voting account.
The "precheck" for gasless was using the wrong address, and failed if you used a delegate contract. Fixed now.
Simplified the "useLockedMKR" hook to only have 1 parameter

Reuse voting account trhough app and fix precheck gasless

---

lib/utils.ts
modules/polling/api/fetchPollTally.ts
modules/polling/types/pollTally.d.ts
modules/tags/constants/poll-tags-mapping.json

In tally calculation converting a BigNumber with `.toNumber()` had a result that was cast using exponential notation `9.59688000646e-7`. Using `.toFixed()` will always return a value in normal notation. Now that result is a string, so I had to change the type as well.

use .toFixed instead of .toNumber to avoid exponential notation

---

lib/theme/colors.js
modules/address/components/AddressDelegatedTo.tsx
modules/address/components/AddressIconBox.tsx
modules/app/components/SystemStatsSidebar.tsx
modules/app/components/TxFinal.tsx
modules/app/components/TxInProgress.tsx
modules/app/components/layout/header/AccountBox.tsx
modules/app/components/layout/header/TransactionBox.tsx
modules/comments/components/CommentItem.tsx
modules/delegates/components/DelegateDetail.tsx
modules/delegates/components/DelegatedByAddress.tsx
modules/delegates/components/DelegatesSystemInfo.tsx
modules/delegates/components/modals/Confirm.tsx
modules/esm/components/ESMHistory.tsx
modules/esm/components/ShutdownModal.tsx
modules/esm/components/burnModal/BurnTxSuccess.tsx
modules/executive/components/VoteModal/DefaultView.tsx
modules/polling/components/BallotBox.tsx
modules/polling/components/PollCreateModal.tsx
modules/polling/components/PollVoteHistoryItem.tsx
modules/polling/components/VotesByAddress.tsx
modules/polling/components/review/ReviewBox.tsx
modules/web3/components/EtherScanLink.tsx
modules/web3/components/EtherscanLink.tsx
modules/web3/helpers/chain.ts
pages/account.tsx
pages/custom-spell/[address].tsx
pages/executive/[proposal-id].tsx
pages/executive/create.tsx
pages/polling/review.tsx

Fixes on styles, refactor all links to etherscan to reuse component so we can handle logic to display gasless info

Fixes for QA and move all links to etherscanlink component

---

pages/api/generate-test-signature.ts

An api endpoint that uses metamask/eth-sig-util and a psuedo-randomly generated private key to create a valid signature for gasless voting that TechOps can use to test the relayer
To test: visit https://governance-portal-v2-git-generate-signature-api-dux-core-unit.vercel.app/api/generate-test-signature?network=goerli
or 
https://governance-portal-v2-git-generate-signature-api-dux-core-unit.vercel.app/api/generate-test-signature?network=mainnet

Generate test signature api

---

modules/executive/components/VoteModal/DefaultView.tsx
modules/executive/components/VoteModal/index.tsx

Fix vote modal width and content

---

modules/address/components/AddressMKRDelegatedStats.tsx
modules/app/components/layout/header/VotingWeight.tsx
modules/delegates/components/DelegateMKRDelegatedStats.tsx
modules/mkr/helpers/getMKRVotingWeight.ts
modules/mkr/hooks/useMKRVotingWeight.ts
modules/polling/components/VotingWeight.tsx
modules/polling/components/poll-vote-input/QuickVote.tsx

It fixes the bug introduced during the last update that would not let delegates vote due to the MKR balance of their delegate contract not being fetched by passing a boolean value dynamically for the components that should display the MKR value of the owned delegate contract.
If you have a delegate contract on Goerli, try to vote on polls.
The MKR balance of the delegate contract should be displayed on all of the account balance sections when connected to the account that owns the delegate contract.
I set up a delegate contract on Goerli for testing and I was able to vote:

Fix mkr balances not showing for delegates

---

modules/app/components/ResourceBox.tsx

https://app.shortcut.com/dux-makerdao/story/2068/create-documentation-for-manual-poll-voting-on-etherscan
Adds link to voting with etherscan manual on polling page

add a link to manual on etherscan poll voting

---

.github/workflows/e2e.yml
.github/workflows/unit.yml

We'll need to update the GitHub actions that rely on node12 since it's deprecated now. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
cc @eskp @sanbotto @OleksandrUA @cristidas @jeannettemcd @zdumitru

update action version

---

pages/api/address/[address]/delegated-to.ts
pages/api/address/[address]/index.ts
pages/api/address/stats.ts
pages/api/comments/executive/[address].ts
pages/api/comments/polling/[poll-id].ts
pages/api/delegates/index.ts
pages/api/executive/[proposal-id].ts
pages/api/executive/all-locks.ts
pages/api/executive/index.ts
pages/api/executive/supporters.ts
pages/api/polling/[slug].ts
pages/api/polling/all-polls.ts
pages/api/polling/tally/[poll-id].ts

Add docs for supporters and all-locks endpoints
Add summary for endpoints so it shows without having to click to drill down

Add swagger docs for supporters, all-locks endpoint

---

modules/app/components/filters/SearchBar.tsx
modules/delegates/components/DelegateAvatarName.tsx
modules/delegates/components/DelegateOverviewCard.tsx
modules/delegates/components/filters/DelegatesSortFilter.tsx
modules/delegates/stores/delegatesFiltersStore.ts
modules/gql/queries/delegates.ts
pages/delegates/index.tsx

This PR tries to fix some issues discovered during QA
- Keep filters when you visit a delegate detail page and the press the "< Back to all delegates" button.
- Sort filter button shows right selected value after coming from delegate detail page. It was showing the filter without text.
- Change from "Delegate" to "Delegate MKR" in the delegate card.
- Apply reset to the sort button
- FIX: When you search by text (applying filters optionally), visit the profile and back the search term disappeared and the filter by text isn't applied.
- Perform request keeping active filters when user clears the name field.

Delegates list QA - Sorting filter and go back from detail screen

---

modules/delegates/helpers/formatDelegationHistoryChart.ts

Fixes an inconsistency in the way the way that days since the start of a year is calculated, that would cause the metrics page to try to render a graph with no data points on it, causing an error.
Before: (on goerli) https://vote.makerdao.com/address/0xe2b5b6045ddfd171a5550a2ff4ffcf21f8a2d238#metrics
After: (on goerli) https://governance-portal-v2-7tfvtejvj-dux-core-unit.vercel.app/address/0xe2b5b6045ddfd171a5550a2ff4ffcf21f8a2d238#metrics
Before:
After:

standardize days since Jan 1st calculation

---

modules/polling/components/VotesByAddress.tsx
pages/executive/[proposal-id].tsx
pages/polling/[poll-hash].tsx

https://app.shortcut.com/dux-makerdao/story/2152/limit-number-of-rendered-voters-on-poll-detail-executive-detail
It reduces the number of poll voters and executive supporters rendered on the frontend during the first load and adds a `Load More` button to render 10 more entries on demand, as well as a text to let users know when there are no more voters to load.

Render less poll voters and executive supporters on first page load

---

modules/polling/polling.constants.ts

It changes the URL of the aggregated polls files and hash files for mainnet and goerli for URLs on the Maker GitHub orgs

Change aggregated polls files URLs

---

pages/executive/create.tsx
pages/polling/create.tsx

Display the markdown in the create page (both polling and exec) the same way it's displayed on the actual polling and exec pages
Before
After

better handle markdown in create page

---

modules/polling/api/fetchPollBy.ts
modules/polling/components/MobileVoteSheet.tsx
package.json
pages/api/polling/[poll-id-or-slug].ts
pages/api/polling/tally/[poll-id].ts
pages/executive/create.tsx
pages/polling/[poll-hash].tsx
pages/polling/create.tsx

#798 polls not being fetched by pollId
#801 markdown overflow on create page

Fixes: polls not being fetched by pollId, markdown overflow on create page

---

modules/polling/api/fetchPolls.ts

It ensure the `partial-active-polls` are re-fetched if their cache key is not valid or not found

 Active polls cache fix

---

modules/address/components/AddressIconBox.tsx
modules/delegates/helpers/splitDelegateName.ts
modules/executive/api/fetchExecutiveVoteTally.ts

- Fix an issue where executive supporters were not being fetched due to an Alchemy rate limitation for the batch RPC requests
- Split the aligned delegate names into 2 rows in mobile screens, that way the delegate name will always be visible regardless of the length of the AVC name

Executive supporters batch requests + mobile delegate names

---

modules/mkr/components/MkrLiquiditySidebar.tsx

Adds new pool and distinguishes between the two uniswap v2 pools

Add new pool to liquidity panel

---

modules/delegates/hooks/useDelegateContractExpirationDate.ts
modules/migration/components/MigrationBanner.tsx
modules/migration/hooks/useLinkedDelegateInfo.tsx
modules/migration/hooks/useMigrationStatus.tsx
pages/polling/[poll-hash].tsx

https://app.shortcut.com/dux-makerdao/story/2412/update-poll-detail-links
https://app.shortcut.com/dux-makerdao/story/2405/remove-migration-banner-for-shadow-delegates
- Add a link to the poll copy review section in the poll detail page
- Check if the user delegate address is a shadow delegate, and if so, hide the delegate migration banner

Feat: poll review link & no delegate migration for shadow delegates

---

modules/polling/components/PollWinningOptionBox.tsx

If we're showing the default option in the poll banner text, then don't show any of the other leading options.
Before:
After:
This poll on goerli on prod shows the & 1 more, when it shouldn't: https://vote.makerdao.com/polling/QmNgQhcX

only one option when defaulting to default value

---

lib/matter.ts
modules/avcs/api/fetchAvcs.ts
modules/delegates/api/fetchGithubDelegates.ts
modules/executive/api/parseExecutive.ts
modules/polling/api/fetchPollMetadata.ts
modules/polling/helpers/__tests__/parsePollMetadata.spec.ts
modules/polling/helpers/__tests__/validatePollParameters.spec.ts
modules/polling/helpers/__tests__/validator.spec.ts
modules/polling/helpers/parsePollMetadata.ts
modules/polling/helpers/validator.ts
pages/executive/create.tsx

use the same config in all gray-matter matter() calls

only use matterWrapper

---

middleware.ts
modules/app/components/layout/header/AccountSelect.tsx
modules/web3/helpers/checkInjectedProvider.ts
modules/web3/hooks/useEagerlyConnect.ts
package.json
yarn.lock

Fix an issue that prevents MetaMask from connecting on Firefox

Fix MetaMask connection on Firefox

---

modules/web3/components/NetworkAlertModal.tsx
modules/web3/helpers/chain.ts

show the unsupported network modal if connected on goerli. The user then gets disconnected when they dismiss the modal

goerli unsupported

---

middleware.ts

- Modify middleware to only return request headers in the `NextResponse.next.request` object
- Remove request headers from the response headers, and only set the CSP in the response headers

Modify middleware to not return request headers in response object

---

.github/workflows/e2e.yml
playwright/esmodule.spec.ts
playwright/polling.spec.ts

- add a test to poll vote with legacy system
Tried to add a test for gasless voting, but it seems that our mock connector doesn't support eth_signTypedData_v4. We create the mock connector by extending ether's Eip1193Bridge, which doesn't support sign typed data. So it would be a bit of to update it to handle it I think, I left that test skipped.

add polling e2e

---

modules/web3/connections/index.ts
modules/web3/constants/wallets.ts
modules/web3/hooks/useTenderlyWindowBindings.tsx

skip mock connector code if USE_MOCK_WALLET isn't true or if NODE ENV is production

Tenderly updates

---

modules/delegates/api/fetchDelegatedTo.ts
modules/gql/queries/subgraph/allDelegations.ts
modules/gql/queries/subgraph/delegateHistoryArray.ts
modules/gql/queries/subgraph/delegatorHistory.ts
modules/web3/constants/networks.ts

Fix history amounts, and expiration dates, increase page limit

---

modules/web3/constants/addresses.ts
modules/web3/constants/chainID.ts
playwright/forkVnet.ts

And update sepolia arbitrum address

Update to Sep 30 vnet

---

modules/address/components/AddressDelegatedTo.tsx
modules/delegates/components/DelegateMKRDelegatedStats.tsx
modules/delegates/components/DelegateOverviewCard.tsx
modules/delegates/components/DelegatedByAddress.tsx
modules/delegates/components/modals/UndelegateModal.tsx
modules/migration/components/DelegateExpirationOverviewCard.tsx
modules/mkr/hooks/useMkrDelegatedByUser.ts

Also shorten (Seal Module) to (Seal) as it was too much text on mobile

Show correct delegate amounts in undelegate modal

---

modules/app/components/TxIndicators.tsx
modules/cache/cache.ts
modules/polling/components/MobileVoteSheet.tsx

- Replace the use of `redis.keys()` for `redis.scan()` which is optimized for production
- Batch exec proposals scans to 100 at a time
- Batch exec proposals deletions so they are deleted in groups of 100 instead of deleting them one by one

Batch cached execs fetches and deletions

---

modules/app/components/TxIndicators.tsx
modules/cache/cache.ts
modules/polling/components/MobileVoteSheet.tsx

* Batch cached execs fetches and deletions
* Dynamically import lottie

Dev -> Master: Batch cached execs fetches and deletions

---

modules/executive/api/fetchExecutives.ts

Fix issue with address comparison, which caused page load error with proposal id executive page.
https://vote.makerdao.com/executive/0x70254bd530684cf4a6323f51098fa39aae6130b6
Visit https://vote.makerdao.com/address/0xa16d0708706245e5e27ac8f118776f5ed1c78d90#comments
Click View Executive

Fix issue with address comparison

---

modules/executive/api/fetchExecutiveVoteTallyWithSubgraph.ts
modules/gql/queries/subgraph/allSpellVotes.ts
pages/api/executive/supporters.ts

Update the api/executive/supporters endpoint to use the subgraph instead of making a ton of rpc calls.
We'd need to deploy the subgraph update to production before deploying this.

Exec supporters subgraph (both legacy and future app?)

---

modules/app/components/layout/header/AccountSelect.tsx

Update AccountSelect component to display 'Connected' when the wallet is selected and disable the button accordingly
Connect to wallet, then go to "change", see that the active wallet button is disabled and reads "Connected"

Disable active wallet button

---

modules/mkr/components/MKRInput.tsx

Fix MKRInput component to remove commas from formatted value before setting current value string
Try to use "Set max" with a number over 999 on the MKRInput component

Fix MKRInput set max for large amounts

---

playwright/delegates.spec.ts

Temporary workaround to fix the delegates.spec
The delegates v2 contracts don't show up as contracts in the tenderly fork so interactions with those delegates in the fork fail.

Sort the delegates list before test

---

yarn.lock

- [Bump tar-fs from 2.1.1 to 2.1.2](https://github.com/makerdao/governance-portal-v2/commit/5a4b4dfebacb5248d2e7f3ec98a94f618b7c15b0)
- [Bump vite from 6.2.3 to 6.2.4](https://github.com/makerdao/governance-portal-v2/commit/5065b62655544ef488026d1b08e90ebdfbd2e9a8)

Dependabot updates - April 02

---

lib/theme/icons.tsx
modules/wagmi/config/config.default.ts

- adds an option for generic injected connector to support additional browser wallets like Rabby

add support for injected browser wallet

---

modules/contracts/ethers/abis.ts
modules/contracts/generated.ts
modules/executive/hooks/useVotedProposals.ts
pages/account.tsx
wagmi.config.ts

- Add logic for delegates to vote for address(0) after they create their delegate contract, while the chief contract is not `live`
- Add copy and UI elements to handle the address(0) voting and states
Video of the flow (it was too large to paste in GitHub):
https://discord.com/channels/836646301986848768/850083386260324382/1357446818895626322

SKY: address(0) vote

---

modules/wagmi/config/config.default.ts

Enables `multiInjectedProviderDiscovery` to support multiple injected wallets

Multi injected discovery

---

pages/executive/[proposal-id].tsx

Fixes the loading state for a proposal that isn't prebuilt by not immediately showing a 404 
Load a proposal, such as `/executive/0x6D89a389C59113a9DA17f094c9b8772A97854593` and see that it shows loading state rather than a 404 while it fetches the spell data.
Before:
After:

Add loading indicator for proposal page, prevent 404 showing prematurely

---

modules/delegates/api/fetchDelegates.ts
modules/delegates/components/DelegateMKRDelegatedStats.tsx
modules/gql/hooks/useLandingPageDelegates.ts
modules/home/api/fetchLandingPageData.ts
modules/mkr/hooks/useSkyVotingWeight.ts
modules/polling/api/fetchPolls.ts
modules/polling/api/getPollTags.ts
pages/index.tsx
scripts/fetchTags.mjs

- Update Github URL for fetching poll tags to use the new metadata repo
- Update poll fetching logic to first fetch the polls, then the poll tag mapping and then attach the poll tags to the corresponding poll (previously the tags were coming along the poll from the aggregated file)
- Fix a delegate fetching bug that was displaying one shadow delegate when you query for only aligned delegates
- Update logic to display error message in the landing page to only be shown when there is an actual error fetching delegates, and not be displayed whenever the arrays are empty (which is the initial state when loading the page)
- Update a couple of places that were rendering an skeleton when the data was actually 0 (falsey value)

Fix metadata bugs

---

modules/delegates/components/modals/Confirm.tsx
modules/delegates/components/modals/DelegateModal.tsx
modules/delegates/components/modals/InputDelegateSky.tsx
modules/delegates/components/modals/UndelegateModal.tsx

Enhance the ConfirmContent component to accept a prepareError prop, allowing for error handling during transaction preparation. Update DelegateModal and UndelegateModal to pass the prepareError state, improving user feedback in case of errors.

Add prepareError prop to ConfirmContent and related modals

---

lib/config.ts
modules/delegates/components/DelegateOverviewCard.tsx
modules/delegates/components/ManageDelegation.tsx
modules/delegates/components/TopDelegates.tsx
modules/delegates/hooks/useDelegateCreate.ts
modules/delegates/hooks/useDelegateLock.ts
modules/esm/hooks/useEsmBurn.ts
modules/esm/hooks/useEsmShutdown.ts
modules/executive/components/ExecutiveOverviewCard.tsx
modules/executive/hooks/useChiefVote.ts
modules/executive/hooks/useDelegateVote.ts
modules/executive/hooks/useVoteProxyVote.ts
modules/mkr/components/Deposit.tsx
modules/mkr/hooks/useLock.ts
modules/polling/components/BallotBox.tsx
modules/polling/components/ChoiceSummary.tsx
modules/polling/components/poll-vote-input/QuickVote.tsx
modules/polling/context/BallotContext.tsx
modules/polling/hooks/usePollCreate.ts
modules/web3/hooks/useApproveUnlimitedToken.ts
next.config.js
pages/esmodule.tsx
pages/polling/create.tsx
tenderlyTestnetData.json

TODO:
- Add a `READ_ONLY` env var that can be used to determine if contract interactions will be disabled
- Disable all write contract interactions in the web app except for chief free (withdraw MKR), old chief free, delegate free (undelegating) and IOU tokens approval when the `READ_ONLY` env var is set to `true`
- Disable some buttons based on the `READ_ONLY` env var to avoid triggering modals with dead ends
List of interactions disabled:
- Poll creation
- Poll vote (legacy and gasless)
- Token approvals for DAI and MKR (still allowed for IOU and IOU_OLD as those are required for withdrawing)
- Chief lock - MKR deposit (EOA and proxy contract)
- Executive vote (EOA, proxy contract and delegate)
- Delegate contract creation
- Delegate lock
- ESM burn and ESM shutdown
Attempt to perform …

Legacy app: Disable write contract interactions

---

lib/string.ts
modules/delegates/components/DelegateMKRChart.tsx
modules/home/api/fetchLandingPageData.ts
modules/home/components/GovernanceStats.tsx

Truncate numbers greater than 1B on the homepage governance stats, and also numbers greater than 1 million on the delegate chart

Truncate some large numbers

---

modules/home/components/Participation.tsx

Before:
After
We can always add this back later, but removing this for now since the participation chart doesn't load and throws errors

remove parts of participation section for now

---

modules/app/components/SystemStatsSidebar.tsx
modules/executive/api/fetchMkrInChief.ts
modules/home/components/GovernanceStats.tsx

Fixes a bug where it was showing 0 SKY in Chief on the homepage and in the sidebar
And fix decimal bug for total mkr delegated

use Sky for sky in cheif stat

---

__tests__/pages/account.test.tsx
lib/theme/colors.ts
modules/app/components/layout/header/Banner.tsx
pages/account.tsx

- Remove redundant alert in delegate creation card
- Only show checkbox when user has sky in chief
- Make the banner an InternalLink, not an ExternalLink
- Update color of disabled primary buttons in dark mode
- Improve wording
- update unit tests
Before
After

Improve delegate creation flow

---

.github/workflows/e2e.yml
modules/polling/components/VotingWeight.tsx
playwright/delegates.spec.ts
playwright/esmodule.spec.ts
playwright/executives.spec.ts
playwright/fixtures/delegate.ts
playwright/fixtures/executive.ts
playwright/fixtures/polling.ts
playwright/helpers/delegateMkr.ts
playwright/helpers/depositMkr.ts
playwright/polling.spec.ts

- Test that all write actions are disabled except for undelegating and withdrawing
Delegates:
- Verify delegating is disabled
- Test successfully undelegating after delegating from the API
ESM:
- Verify user can't interact with the burn button
Polling:
- Verify user can't add polls to ballot and can't submit ballot
Executive:
- Verify depositing is disabled
- Verify user can't vote even after depositing through the API
- Test successfully withdrawing MKR from chief

Update E2E tests to account for the read mode state

---

modules/gql/queries/subgraph/pollTimes.ts
modules/polling/api/fetchAllCurrentVotes.ts

- fetch poll start / end times from the arbitrum subgraph
- base the voting weight on the weight at the poll end, not the time of the vote

Poll history page fixes

---

modules/polling/api/fetchPolls.ts

This allows for handling polls where the metadata file name has special characters in it like spaces.
Before, we were trying to encode an already encoded URL which made the matching not work.
Now we can see poll 1506 on the testnet with this update.

decode paths before comparison instead of encoding them

---

modules/app/components/layout/Header.tsx
modules/delegates/components/TopDelegates.tsx
modules/home/components/Stats.tsx
pages/delegates/index.tsx
pages/polling.tsx

Mobile:
- Increase padding in homepage cards
- Fix size and background of the header menu popup
- Change color of texts over the image background that were almost unreadable

Fix visual bugs on mobile

---

modules/delegates/components/DelegateOverviewCard.tsx
modules/executive/components/CurrentlySupportingExecutive.tsx

TODO:
If no executive support is detected from the subgraph, check if delegate is supporting address(0)

Check if delegate is supporting address zero

---

modules/app/components/layout/header/VotingWeight.tsx
modules/delegates/api/getDelegatesRepositoryInfo.ts
modules/executive/api/fetchExecutives.ts
modules/polling/api/fetchPolls.ts
modules/polling/components/VotingWeight.tsx
modules/polling/polling.constants.ts

When NEXT_PUBLIC_VERCEL_ENV = "development" we show the forked metadata instead of the makerdao metadata.
Alternatively, we could add a different environment variable that we use for this instead, if we want to default to makerdao metadata on development. What do we think?

Add mainnet staging metadata

---

docs/POLL_PARAMETERS.md
modules/polling/api/getPollTags.ts

This PR updates all references to the MakerDAO polls source repository from the old `makerdao/community` repository to the new, dedicated `makerdao/polls` repository.
1.  **Verify Documentation Link:**
*   Open the `docs/POLL_PARAMETERS.md` file.
*   Confirm that the link in the first paragraph, "MakerDAO polls repo", now points to `https://github.com/makerdao/polls` and that the link is accessible.
2.  **Test Poll Tag Fetching:**
*   Run the application locally.
*   Navigate to the part of the governance portal where polls and their tags are displayed.
*   Confirm that poll tags are still being fetched and displayed correctly. This ensures the `getPollTags` API call to the updated URL is successful.

Add link to updated poll tags json

---

.github/workflows/e2e.yml
.npmrc
package.json

- Specify the pnpm version to use in the package.json
- Sets the minimum release age for new packages to 24 hours, so that a new package version needs to be at least 24 hours old before it can be installed in the monorepo
- Remove old pnpm configs that were using the default values and update the preferred file for configs from the `.npmrc` file to the `pnpm-workspace.yaml` file

Pnpm minimum release age
